<?php

return [
    'pages' => [
        [
            'page_key' => 'home',
            'title' => 'Home',
            'slug' => 'home',
            'status' => 1,
            'sort_order' => 1,
            'subtitle' => 'Internationally Benchmarked Education for Global Excellence',
            'display_order' => 1,
            'show_in_navigation' => 1,
            'cta_button_text' => 'Apply Now',
            'cta_button_link' => 'admissions',
        ],
        [
            'page_key' => 'about',
            'title' => 'About Us',
            'slug' => 'about-us',
            'status' => 1,
            'sort_order' => 2,
            'subtitle' => 'Our History, Values, and Institutional Direction',
            'display_order' => 2,
            'show_in_navigation' => 1,
        ],
        [
            'page_key' => 'programs',
            'title' => 'Academic Programmes',
            'slug' => 'academic-programmes',
            'status' => 1,
            'sort_order' => 3,
            'subtitle' => 'Programme Levels, Delivery Model, and Student Experience',
            'display_order' => 3,
            'show_in_navigation' => 1,
        ],
        [
            'page_key' => 'admissions',
            'title' => 'Admissions',
            'slug' => 'admissions',
            'status' => 1,
            'sort_order' => 4,
            'subtitle' => 'Entry Requirements, Application Steps, and Credit Transfer',
            'display_order' => 4,
            'show_in_navigation' => 1,
            'cta_button_text' => 'Begin Application',
            'cta_button_link' => 'contact-us',
        ],
        [
            'page_key' => 'research',
            'title' => 'Research & Innovation',
            'slug' => 'research-and-innovation',
            'status' => 1,
            'sort_order' => 5,
            'subtitle' => 'Knowledge Creation, Partnerships, and Institutional Impact',
            'display_order' => 5,
            'show_in_navigation' => 1,
        ],
        [
            'page_key' => 'contact',
            'title' => 'Contact Us',
            'slug' => 'contact-us',
            'status' => 1,
            'sort_order' => 6,
            'subtitle' => 'Official Communication Channels and Enquiries',
            'display_order' => 6,
            'show_in_navigation' => 1,
        ],
    ],
    'sections' => [
        [
            'page_key' => 'home',
            'section_key' => 'hero_slider',
            'title' => 'Prime International Institute of Excellence (PIIE)',
            'subtitle' => 'A modern higher education institution established in Uganda for flexible, technology-enabled learning of genuine international standard.',
            'content' => 'Prime International Institute of Excellence serves ambitious learners across Uganda, East Africa, and the wider world through rigorous academic programmes, professional relevance, and accessible Open, Distance and e-Learning.',
            'status' => 1,
            'sort_order' => 1,
        ],
        [
            'page_key' => 'about',
            'section_key' => 'about_institution',
            'title' => 'About Us',
            'subtitle' => 'Prime International Institute of Excellence (PIIE)',
            'content' => "Prime International Institute of Excellence (PIIE) is a modern higher education institution established in Uganda with a clear mandate: to deliver academic programmes of genuine international standard through flexible, technology-enabled learning that is accessible to ambitious learners across Uganda, East Africa, and the wider world.\n\nPIIE was founded on the conviction that academic excellence and professional relevance are complementary dimensions of a single educational mission. Every programme we offer, every faculty member we engage, and every student we admit reflects this conviction.",
            'status' => 1,
            'sort_order' => 2,
        ],
        [
            'page_key' => 'about',
            'section_key' => 'origin_history',
            'title' => 'Origin and History',
            'subtitle' => 'The Founding of PIIE',
            'content' => "Prime International Institute of Excellence was founded in 2026 by academic and institutional leaders responding to a gap in Uganda's higher education landscape: the shortage of institutions combining genuine academic rigour, flexible delivery models, and an explicitly international orientation.\n\nFrom its headquarters in Nansana Municipality, Wakiso District, Uganda, PIIE has grown in student enrolment, academic staff capacity, programme portfolio, and institutional partnerships while ensuring that geography is never a barrier to academic achievement.",
            'status' => 1,
            'sort_order' => 3,
        ],
        [
            'page_key' => 'about',
            'section_key' => 'institutional_character',
            'title' => 'Institutional Character',
            'subtitle' => 'What Distinguishes PIIE',
            'content' => "PIIE is defined by uncompromising academic standards, international orientation, technology-driven learning, a strong career and leadership focus, and inclusive excellence. Assessments are rigorous, programmes are benchmarked against international standards, and every learner is prepared to compete and lead in a globalised world.",
            'status' => 1,
            'sort_order' => 4,
        ],
        [
            'page_key' => 'about',
            'section_key' => 'vision_mission_motto',
            'title' => 'Vision, Mission, and Motto',
            'subtitle' => 'The Institutional Direction of PIIE',
            'content' => "Vision: To be a premier internationally recognised institution of academic excellence, shaping transformational leaders, innovators, entrepreneurs, and globally competitive professionals who drive sustainable development across Africa and the wider world.\n\nMission: To deliver rigorous, innovative, and internationally benchmarked academic programmes through flexible, technology-enabled learning systems that equip learners with the knowledge, skills, ethical values, and leadership capabilities required for professional excellence, entrepreneurial success, and meaningful contribution to society in a rapidly evolving global economy.\n\nMotto: Strive. Excel. Lead.",
            'status' => 1,
            'sort_order' => 5,
        ],
        [
            'page_key' => 'about',
            'section_key' => 'core_values',
            'title' => 'Core Values',
            'subtitle' => 'The Standards That Govern the Institution',
            'content' => "Excellence, Integrity, Innovation, Global Competitiveness, Entrepreneurial Spirit, Inclusivity, and Accountability define all academic, administrative, and stakeholder engagements at PIIE. These values shape programme quality, student support, governance, and the credibility of every qualification we award.",
            'status' => 1,
            'sort_order' => 6,
        ],
        [
            'page_key' => 'about',
            'section_key' => 'educational_philosophy',
            'title' => 'Institutional Philosophy',
            'subtitle' => 'Our Philosophy of Education',
            'content' => "At PIIE, higher education serves four interconnected purposes: the development of intellectual capacity, the cultivation of professional competence, the formation of ethical character, and the preparation of individuals for meaningful participation in society.\n\nWe believe education is not the accumulation of information but the transformation of a person's capacity to understand, reason, create, and lead. We also believe that rigour and flexibility are not opposites. PIIE was built to demonstrate that the highest academic standards can coexist with the digital accessibility modern learners require.",
            'status' => 1,
            'sort_order' => 7,
        ],
        [
            'page_key' => 'about',
            'section_key' => 'why_choose_us',
            'title' => 'Why Choose PIIE',
            'subtitle' => 'Why Ambitious Learners Choose PIIE',
            'content' => "PIIE offers internationally benchmarked programmes, flexible ODeL delivery without compromising quality, qualifications validated by recognised partner universities, experienced postgraduate-credentialed faculty, a complete digital academic experience, affordable and transparent fees, credit transfer pathways, leadership and entrepreneurship development, and personalised support from enrolment to graduation.",
            'status' => 1,
            'sort_order' => 8,
        ],
        [
            'page_key' => 'about',
            'section_key' => 'welcome_messages',
            'title' => 'Welcome Messages',
            'subtitle' => 'Leadership Perspectives',
            'content' => 'PIIE leadership welcomes students, partners, employers, alumni, and stakeholders with a shared commitment to quality, integrity, and long-term learner impact.',
            'status' => 1,
            'sort_order' => 9,
        ],
        [
            'page_key' => 'about',
            'section_key' => 'leadership_team',
            'title' => 'Leadership Team',
            'subtitle' => 'Institutional Leadership',
            'content' => 'The leadership of PIIE provides academic direction, governance oversight, student records stewardship, and institutional administration grounded in excellence and accountability.',
            'status' => 1,
            'sort_order' => 10,
        ],
        [
            'page_key' => 'about',
            'section_key' => 'governance_structure',
            'title' => 'Governance Structure',
            'subtitle' => 'Formal and Transparent Institutional Governance',
            'content' => "Prime International Institute of Excellence is governed by a formal structure composed of the Governing Council, the Director, the Principal, the Academic Registrar, and the Institute Secretary. This framework ensures accountability, academic quality, regulatory compliance, and the long-term integrity of the institution.",
            'status' => 1,
            'sort_order' => 11,
        ],
        [
            'page_key' => 'about',
            'section_key' => 'strategic_plan',
            'title' => 'Strategic Plan (2026 - 2033)',
            'subtitle' => 'Our Strategic Direction',
            'content' => "PIIE's seven-year strategic framework is built around six objectives: academic excellence and programme quality; research, knowledge creation, and innovation; strategic partnerships and institutional networks; technology, digital infrastructure, and learning innovation; institutional sustainability and governance excellence; and student success, graduate impact, and community engagement.",
            'status' => 1,
            'sort_order' => 12,
        ],
        [
            'page_key' => 'programs',
            'section_key' => 'academic_programmes',
            'title' => 'Academic Programmes',
            'subtitle' => 'Programme Levels, Durations, and Fees',
            'content' => "PIIE offers a carefully designed portfolio of academic programmes from Certificate to Masters Degree. All programmes are delivered through the Open, Distance and e-Learning model, combining robust theoretical foundations with practical real-world application.\n\nMasters Degree Programmes: 2 Academic Years (4 Semesters) - UGX 1,200,000 per Semester.\nPostgraduate Diploma Programmes: 1 Academic Year (2 Semesters) - UGX 1,200,000 per Semester.\nBachelor's Degree Programmes: 3 Academic Years (6 Semesters) - UGX 1,000,000 per Semester.\nDiploma Programmes: 2 Academic Years (4 Semesters) - UGX 650,000 per Semester.\nCertificate Programmes: 2 Academic Years (4 Semesters) - UGX 600,000 per Semester.\n\nMasters, Postgraduate Diploma, and Bachelor's programmes are delivered through partnerships with accredited and recognised universities. All courses are offered fully online.",
            'status' => 1,
            'sort_order' => 13,
        ],
        [
            'page_key' => 'programs',
            'section_key' => 'programme_categories',
            'title' => 'Programme Categories',
            'subtitle' => 'Study Pathways at PIIE',
            'content' => 'Choose the study level that matches your qualifications, professional stage, and long-term ambition.',
            'status' => 1,
            'sort_order' => 14,
        ],
        [
            'page_key' => 'programs',
            'section_key' => 'programme_catalog_graduate_school',
            'title' => 'Graduate School',
            'subtitle' => "Master's Degree & Postgraduate Diploma Programmes",
            'content' => 'Postgraduate study designed for leadership, professional growth, and global competitiveness, validated through partnerships with accredited universities.',
            'status' => 1,
            'sort_order' => 28,
        ],
        [
            'page_key' => 'programs',
            'section_key' => 'programme_catalog_business_management',
            'title' => 'Faculty of Business and Management',
            'subtitle' => "Bachelor's Degree, Diploma & National Certificate Programmes",
            'content' => "PIIE's largest faculty, covering business administration, human resources, finance, procurement, public administration, and administrative practice.",
            'status' => 1,
            'sort_order' => 29,
        ],
        [
            'page_key' => 'programs',
            'section_key' => 'programme_catalog_humanities',
            'title' => 'Faculty of Humanities',
            'subtitle' => "Bachelor's Degree, Diploma & National Certificate Programmes",
            'content' => 'Programmes in journalism, media studies, social work, and the creative and performing arts.',
            'status' => 1,
            'sort_order' => 30,
        ],
        [
            'page_key' => 'programs',
            'section_key' => 'programme_catalog_education',
            'title' => 'Faculty of Education',
            'subtitle' => "Bachelor's Degree, Diploma, Bridging & Certificate Programmes",
            'content' => 'Programmes for teaching and early childhood care practitioners, from certificate level through to Bachelor of Education.',
            'status' => 1,
            'sort_order' => 31,
        ],
        [
            'page_key' => 'admissions',
            'section_key' => 'admissions',
            'title' => 'How to Apply',
            'subtitle' => 'Accessible, Merit-Based, and Fully Digital',
            'content' => "PIIE welcomes learners from diverse educational, professional, and personal backgrounds — from recent school leavers to experienced professionals and postgraduate candidates. The admissions process is completed entirely online in seven steps.",
            'status' => 1,
            'sort_order' => 15,
        ],
        [
            'page_key' => 'admissions',
            'section_key' => 'entry_requirements',
            'title' => 'Entry Requirements',
            'subtitle' => 'What You Need to Qualify, by Programme Level',
            'content' => '',
            'status' => 1,
            'sort_order' => 16,
        ],
        [
            'page_key' => 'programs',
            'section_key' => 'online_learning_odel',
            'title' => 'Online and Distance Learning',
            'subtitle' => 'Learn from Anywhere. Achieve Without Limits.',
            'content' => "PIIE operates exclusively through the Open, Distance and e-Learning model. Students study entirely online, access course materials through the Learning Management System, engage with faculty through live virtual sessions and moderated forums, submit assignments digitally, and sit examinations through secure platforms.\n\nThe ODeL model is structured around self-directed study, facilitated sessions, continuous assessment, end-of-semester examinations, and responsive faculty support.",
            'status' => 1,
            'sort_order' => 16,
        ],
        [
            'page_key' => 'research',
            'section_key' => 'research_innovation',
            'title' => 'Research and Innovation',
            'subtitle' => 'Research. Knowledge. Impact.',
            'content' => "Research is central to PIIE's academic mission. The Research and Innovation Centre coordinates original knowledge creation, policy-relevant inquiry, collaborative projects, innovation initiatives, publications, and dissemination across business, public administration, governance, technology, entrepreneurship, finance, higher education, and sustainable development.",
            'status' => 1,
            'sort_order' => 17,
        ],
        [
            'page_key' => 'research',
            'section_key' => 'partnerships_affiliations',
            'title' => 'Partnerships and Collaborations',
            'subtitle' => 'Building Excellence Through Strategic Alliances',
            'content' => "PIIE builds strategic alliances with universities, industry leaders, financial institutions, government agencies, and regulatory bodies that strengthen programme quality, student opportunity, and institutional credibility. Each partnership is evaluated against one test: whether it improves the learner experience and the standing of PIIE qualifications.",
            'status' => 1,
            'sort_order' => 18,
        ],
        [
            'page_key' => 'programs',
            'section_key' => 'student_support_services',
            'title' => 'Student Support Services',
            'subtitle' => 'Your Success is Our Institutional Priority',
            'content' => "PIIE provides academic advising, digital library access, technical and ICT support, career development services, personal counselling and wellness support, financial guidance, alumni mentorship, examination guidance, and dedicated international student support. The student journey is supported from enrolment to graduation and beyond.",
            'status' => 1,
            'sort_order' => 19,
        ],
        [
            'page_key' => 'programs',
            'section_key' => 'international_students',
            'title' => 'International Students',
            'subtitle' => 'A World-Class Institution. Open to the World.',
            'content' => "PIIE welcomes students from across the globe through a fully online delivery model that eliminates relocation requirements while preserving academic rigour. International students benefit from validated qualifications, English-language delivery, affordable fees, global classroom perspectives, and dedicated orientation and advisory support.",
            'status' => 1,
            'sort_order' => 20,
        ],
        [
            'page_key' => 'research',
            'section_key' => 'news_events',
            'title' => 'News and Events',
            'subtitle' => 'Stay Informed. Stay Connected. Stay Ahead.',
            'content' => "The PIIE News and Events page is the central source for institutional announcements, academic highlights, programme updates, partnership news, student achievements, and upcoming events including virtual open days, seminars, conferences, and professional development workshops.",
            'status' => 1,
            'sort_order' => 21,
        ],
        [
            'page_key' => 'admissions',
            'section_key' => 'faqs',
            'title' => 'Frequently Asked Questions',
            'subtitle' => 'Common Questions About PIIE',
            'content' => 'Below are clear answers to common questions from prospective students, enrolled learners, alumni, partners, and other stakeholders.',
            'status' => 1,
            'sort_order' => 22,
        ],
        [
            'page_key' => 'contact',
            'section_key' => 'contact_page',
            'title' => 'Official Communication Channels',
            'subtitle' => 'Consistent Public Contact Information',
            'content' => "Institution Name: Prime International Institute of Excellence. Acronym: PIIE. Headquarters: Nansana Municipality, Wakiso District, Uganda. Office Hours: Monday to Friday and Saturday by official schedule. Sunday and Public Holidays: Closed, while digital enquiries remain accepted and are responded to on the next working day.\n\nThe admissions portal, Learning Management System, and student portal remain accessible twenty-four hours a day, seven days a week.",
            'status' => 1,
            'sort_order' => 23,
        ],
        [
            'page_key' => 'home',
            'section_key' => 'footer_settings',
            'title' => 'Footer',
            'subtitle' => 'Footer information and quick navigation',
            'content' => 'Footer content and official links for Prime International Institute of Excellence.',
            'status' => 1,
            'sort_order' => 24,
        ],
        [
            'page_key' => 'home',
            'section_key' => 'quick_links',
            'title' => 'Quick Links',
            'subtitle' => 'Primary website navigation',
            'content' => 'Shortcut links to key pages and information categories.',
            'status' => 1,
            'sort_order' => 25,
        ],
        [
            'page_key' => 'home',
            'section_key' => 'portals_links',
            'title' => 'Portals Links',
            'subtitle' => 'Admissions and digital portals',
            'content' => 'Access the admissions portal, student systems, and institutional communication channels.',
            'status' => 1,
            'sort_order' => 26,
        ],
        [
            'page_key' => 'home',
            'section_key' => 'social_media_links',
            'title' => 'Social Media Links',
            'subtitle' => 'Official social and digital channels',
            'content' => 'Official social links can be updated here as institutional channels are confirmed.',
            'status' => 1,
            'sort_order' => 27,
        ],
    ],
    'items' => [
        [
            'section_key' => 'programme_categories',
            'item_type' => 'program_category',
            'title' => 'Masters Degree Programmes',
            'subtitle' => '2 Academic Years (4 Semesters)',
            'description' => 'Advanced postgraduate study designed for leadership, professional growth, and global competitiveness.',
            'content' => 'UGX 1,200,000 per semester',
            'status' => 1,
            'sort_order' => 1,
        ],
        [
            'section_key' => 'programme_categories',
            'item_type' => 'program_category',
            'title' => 'Postgraduate Diploma Programmes',
            'subtitle' => '1 Academic Year (2 Semesters)',
            'description' => 'Focused postgraduate pathways for specialised professional advancement and academic progression.',
            'content' => 'UGX 1,200,000 per semester',
            'status' => 1,
            'sort_order' => 2,
        ],
        [
            'section_key' => 'programme_categories',
            'item_type' => 'program_category',
            'title' => 'Bachelor\'s Degree Programmes',
            'subtitle' => '3 Academic Years (6 Semesters)',
            'description' => 'Comprehensive undergraduate programmes delivered through a flexible and rigorous ODeL model.',
            'content' => 'UGX 1,000,000 per semester',
            'status' => 1,
            'sort_order' => 3,
        ],
        [
            'section_key' => 'programme_categories',
            'item_type' => 'program_category',
            'title' => 'Diploma Programmes',
            'subtitle' => '2 Academic Years (4 Semesters)',
            'description' => 'Professionally relevant diploma pathways for career growth, technical capability, and progression.',
            'content' => 'UGX 650,000 per semester',
            'status' => 1,
            'sort_order' => 4,
        ],
        [
            'section_key' => 'programme_categories',
            'item_type' => 'program_category',
            'title' => 'Certificate Programmes',
            'subtitle' => '2 Academic Years (4 Semesters)',
            'description' => 'Accessible entry-level programmes for learners beginning their higher education journey.',
            'content' => 'UGX 600,000 per semester',
            'status' => 1,
            'sort_order' => 5,
        ],
        // ── Graduate School: Master's Degree Programmes ──────────────────
        ['section_key' => 'programme_catalog_graduate_school', 'item_type' => 'programme', 'title' => 'Master of Business Administration (MBA)', 'subtitle' => "Master's Degree", 'content' => '2 Academic Years (4 Semesters)', 'status' => 1, 'sort_order' => 1],
        ['section_key' => 'programme_catalog_graduate_school', 'item_type' => 'programme', 'title' => 'Master of Public Administration and Management (MPAM)', 'subtitle' => "Master's Degree", 'content' => '2 Academic Years (4 Semesters)', 'status' => 1, 'sort_order' => 2],
        ['section_key' => 'programme_catalog_graduate_school', 'item_type' => 'programme', 'title' => 'Master of Science in Human Resource Management (MSHRM)', 'subtitle' => "Master's Degree", 'content' => '2 Academic Years (4 Semesters)', 'status' => 1, 'sort_order' => 3],
        ['section_key' => 'programme_catalog_graduate_school', 'item_type' => 'programme', 'title' => 'Master of Science in Finance (MSF)', 'subtitle' => "Master's Degree", 'content' => '2 Academic Years (4 Semesters)', 'status' => 1, 'sort_order' => 4],
        ['section_key' => 'programme_catalog_graduate_school', 'item_type' => 'programme', 'title' => 'Master of Science in Procurement and Logistics Management (MSPLM)', 'subtitle' => "Master's Degree", 'content' => '2 Academic Years (4 Semesters)', 'status' => 1, 'sort_order' => 5],
        ['section_key' => 'programme_catalog_graduate_school', 'item_type' => 'programme', 'title' => 'Master of Arts in Economics (MAE)', 'subtitle' => "Master's Degree", 'content' => '2 Academic Years (4 Semesters)', 'status' => 1, 'sort_order' => 6],
        ['section_key' => 'programme_catalog_graduate_school', 'item_type' => 'programme', 'title' => 'Master of Educational Planning and Management (MEPM)', 'subtitle' => "Master's Degree", 'content' => '2 Academic Years (4 Semesters)', 'status' => 1, 'sort_order' => 7],
        ['section_key' => 'programme_catalog_graduate_school', 'item_type' => 'programme', 'title' => 'Master of Information Technology (MIT)', 'subtitle' => "Master's Degree", 'content' => '2 Academic Years (4 Semesters)', 'status' => 1, 'sort_order' => 8],
        ['section_key' => 'programme_catalog_graduate_school', 'item_type' => 'programme', 'title' => 'Master of Development Studies (MDS)', 'subtitle' => "Master's Degree", 'content' => '2 Academic Years (4 Semesters)', 'status' => 1, 'sort_order' => 9],
        ['section_key' => 'programme_catalog_graduate_school', 'item_type' => 'programme', 'title' => 'Master of Information Systems (MIS)', 'subtitle' => "Master's Degree", 'content' => '2 Academic Years (4 Semesters)', 'status' => 1, 'sort_order' => 10],
        ['section_key' => 'programme_catalog_graduate_school', 'item_type' => 'programme', 'title' => 'Master of Project Planning and Management (MPPM)', 'subtitle' => "Master's Degree", 'content' => '2 Academic Years (4 Semesters)', 'status' => 1, 'sort_order' => 11],
        ['section_key' => 'programme_catalog_graduate_school', 'item_type' => 'programme', 'title' => 'Master of Science in Public Health (MSPH)', 'subtitle' => "Master's Degree", 'content' => '2 Academic Years (4 Semesters)', 'status' => 1, 'sort_order' => 12],
        // ── Graduate School: Postgraduate Diploma Programmes ─────────────
        ['section_key' => 'programme_catalog_graduate_school', 'item_type' => 'programme', 'title' => 'Post Graduate Diploma in Business Administration (PGDBA)', 'subtitle' => 'Postgraduate Diploma', 'content' => '1 Academic Year (2 Semesters)', 'status' => 1, 'sort_order' => 13],
        ['section_key' => 'programme_catalog_graduate_school', 'item_type' => 'programme', 'title' => 'Post Graduate Diploma in Public Administration and Management (PGDPAM)', 'subtitle' => 'Postgraduate Diploma', 'content' => '1 Academic Year (2 Semesters)', 'status' => 1, 'sort_order' => 14],
        ['section_key' => 'programme_catalog_graduate_school', 'item_type' => 'programme', 'title' => 'Post Graduate Diploma in Educational Planning and Management (PGDEPM)', 'subtitle' => 'Postgraduate Diploma', 'content' => '1 Academic Year (2 Semesters)', 'status' => 1, 'sort_order' => 15],
        ['section_key' => 'programme_catalog_graduate_school', 'item_type' => 'programme', 'title' => 'Post Graduate Diploma in Human Resource Management (PGDHRM)', 'subtitle' => 'Postgraduate Diploma', 'content' => '1 Academic Year (2 Semesters)', 'status' => 1, 'sort_order' => 16],
        ['section_key' => 'programme_catalog_graduate_school', 'item_type' => 'programme', 'title' => 'Post Graduate Diploma in Finance (PGDF)', 'subtitle' => 'Postgraduate Diploma', 'content' => '1 Academic Year (2 Semesters)', 'status' => 1, 'sort_order' => 17],
        ['section_key' => 'programme_catalog_graduate_school', 'item_type' => 'programme', 'title' => 'Post Graduate Diploma in Procurement and Logistics Management (PGDPLM)', 'subtitle' => 'Postgraduate Diploma', 'content' => '1 Academic Year (2 Semesters)', 'status' => 1, 'sort_order' => 18],
        ['section_key' => 'programme_catalog_graduate_school', 'item_type' => 'programme', 'title' => 'Post Graduate Diploma in Project Planning and Management (PGDPPM)', 'subtitle' => 'Postgraduate Diploma', 'content' => '1 Academic Year (2 Semesters)', 'status' => 1, 'sort_order' => 19],
        ['section_key' => 'programme_catalog_graduate_school', 'item_type' => 'programme', 'title' => 'Post Graduate Diploma in Monitoring and Evaluation (PGDME)', 'subtitle' => 'Postgraduate Diploma', 'content' => '1 Academic Year (2 Semesters)', 'status' => 1, 'sort_order' => 20],
        ['section_key' => 'programme_catalog_graduate_school', 'item_type' => 'programme', 'title' => 'Post Graduate Diploma in Public Health (PGDPH)', 'subtitle' => 'Postgraduate Diploma', 'content' => '1 Academic Year (2 Semesters)', 'status' => 1, 'sort_order' => 21],

        // ── Faculty of Business and Management: Bachelor's Degrees ────────
        ['section_key' => 'programme_catalog_business_management', 'item_type' => 'programme', 'title' => 'Bachelor of Business Administration (BBA)', 'subtitle' => "Bachelor's Degree", 'content' => '3 Academic Years (6 Semesters)', 'status' => 1, 'sort_order' => 1],
        ['section_key' => 'programme_catalog_business_management', 'item_type' => 'programme', 'title' => 'Bachelor of Human Resource Management (BHRM)', 'subtitle' => "Bachelor's Degree", 'content' => '3 Academic Years (6 Semesters)', 'status' => 1, 'sort_order' => 2],
        ['section_key' => 'programme_catalog_business_management', 'item_type' => 'programme', 'title' => 'Bachelor of Management Science (BMS)', 'subtitle' => "Bachelor's Degree", 'content' => '3 Academic Years (6 Semesters)', 'status' => 1, 'sort_order' => 3],
        ['section_key' => 'programme_catalog_business_management', 'item_type' => 'programme', 'title' => 'Bachelor of Science in Accounting and Finance (BSAF)', 'subtitle' => "Bachelor's Degree", 'content' => '3 Academic Years (6 Semesters)', 'status' => 1, 'sort_order' => 4],
        ['section_key' => 'programme_catalog_business_management', 'item_type' => 'programme', 'title' => 'Bachelor of Procurement and Logistics Management (BPLM)', 'subtitle' => "Bachelor's Degree", 'content' => '3 Academic Years (6 Semesters)', 'status' => 1, 'sort_order' => 5],
        ['section_key' => 'programme_catalog_business_management', 'item_type' => 'programme', 'title' => 'Bachelor of Public Administration and Management (BPAM)', 'subtitle' => "Bachelor's Degree", 'content' => '3 Academic Years (6 Semesters)', 'status' => 1, 'sort_order' => 6],
        ['section_key' => 'programme_catalog_business_management', 'item_type' => 'programme', 'title' => 'Bachelor of Administrative and Secretarial Practice (BASP)', 'subtitle' => "Bachelor's Degree", 'content' => '3 Academic Years (6 Semesters)', 'status' => 1, 'sort_order' => 7],
        ['section_key' => 'programme_catalog_business_management', 'item_type' => 'programme', 'title' => 'Bachelor of Records Management and Informatics (BRMI)', 'subtitle' => "Bachelor's Degree", 'content' => '3 Academic Years (6 Semesters)', 'status' => 1, 'sort_order' => 8],
        ['section_key' => 'programme_catalog_business_management', 'item_type' => 'programme', 'title' => 'Bachelor of Arts in Economics (BAE)', 'subtitle' => "Bachelor's Degree", 'content' => '3 Academic Years (6 Semesters)', 'status' => 1, 'sort_order' => 9],
        ['section_key' => 'programme_catalog_business_management', 'item_type' => 'programme', 'title' => 'Bachelor of Development Studies (BDS)', 'subtitle' => "Bachelor's Degree", 'content' => '3 Academic Years (6 Semesters)', 'status' => 1, 'sort_order' => 10],
        // ── Faculty of Business and Management: Diploma Programmes ───────
        ['section_key' => 'programme_catalog_business_management', 'item_type' => 'programme', 'title' => 'Diploma in Business Administration (DBA)', 'subtitle' => 'Diploma', 'content' => '2 Academic Years (4 Semesters)', 'status' => 1, 'sort_order' => 11],
        ['section_key' => 'programme_catalog_business_management', 'item_type' => 'programme', 'title' => 'Diploma in Public Administration and Management (DPAM)', 'subtitle' => 'Diploma', 'content' => '2 Academic Years (4 Semesters)', 'status' => 1, 'sort_order' => 12],
        ['section_key' => 'programme_catalog_business_management', 'item_type' => 'programme', 'title' => 'Diploma in Accounting and Finance (DAF)', 'subtitle' => 'Diploma', 'content' => '2 Academic Years (4 Semesters)', 'status' => 1, 'sort_order' => 13],
        ['section_key' => 'programme_catalog_business_management', 'item_type' => 'programme', 'title' => 'Diploma in Procurement and Logistics Management (DPLM)', 'subtitle' => 'Diploma', 'content' => '2 Academic Years (4 Semesters)', 'status' => 1, 'sort_order' => 14],
        ['section_key' => 'programme_catalog_business_management', 'item_type' => 'programme', 'title' => 'Diploma in Administrative and Secretarial Practice (DASP)', 'subtitle' => 'Diploma', 'content' => '2 Academic Years (4 Semesters)', 'status' => 1, 'sort_order' => 15],
        // ── Faculty of Business and Management: National Certificates ────
        ['section_key' => 'programme_catalog_business_management', 'item_type' => 'programme', 'title' => 'National Certificate in Accounting and Finance (NCAF)', 'subtitle' => 'National Certificate', 'content' => '2 Academic Years (4 Semesters)', 'status' => 1, 'sort_order' => 16],
        ['section_key' => 'programme_catalog_business_management', 'item_type' => 'programme', 'title' => 'National Certificate in Business Administration (NCBA)', 'subtitle' => 'National Certificate', 'content' => '2 Academic Years (4 Semesters)', 'status' => 1, 'sort_order' => 17],
        ['section_key' => 'programme_catalog_business_management', 'item_type' => 'programme', 'title' => 'National Certificate in Human Resource Management (NCHRM)', 'subtitle' => 'National Certificate', 'content' => '2 Academic Years (4 Semesters)', 'status' => 1, 'sort_order' => 18],
        ['section_key' => 'programme_catalog_business_management', 'item_type' => 'programme', 'title' => 'National Certificate in Procurement and Logistics Management (NCPLM)', 'subtitle' => 'National Certificate', 'content' => '2 Academic Years (4 Semesters)', 'status' => 1, 'sort_order' => 19],
        ['section_key' => 'programme_catalog_business_management', 'item_type' => 'programme', 'title' => 'National Certificate in Public Administration and Management (NCPAM)', 'subtitle' => 'National Certificate', 'content' => '2 Academic Years (4 Semesters)', 'status' => 1, 'sort_order' => 20],
        ['section_key' => 'programme_catalog_business_management', 'item_type' => 'programme', 'title' => 'National Certificate in Records and Information Management (NCRIM)', 'subtitle' => 'National Certificate', 'content' => '2 Academic Years (4 Semesters)', 'status' => 1, 'sort_order' => 21],
        ['section_key' => 'programme_catalog_business_management', 'item_type' => 'programme', 'title' => 'National Certificate in Secretarial and Office Management (NCSOM)', 'subtitle' => 'National Certificate', 'content' => '2 Academic Years (4 Semesters)', 'status' => 1, 'sort_order' => 22],
        ['section_key' => 'programme_catalog_business_management', 'item_type' => 'programme', 'title' => 'National Certificate in Tourism and Hospitality Management (NCTHM)', 'subtitle' => 'National Certificate', 'content' => '2 Academic Years (4 Semesters)', 'status' => 1, 'sort_order' => 23],
        ['section_key' => 'programme_catalog_business_management', 'item_type' => 'programme', 'title' => 'National Certificate in Hotel and Institutional Catering (NCHIC)', 'subtitle' => 'National Certificate', 'content' => '2 Academic Years (4 Semesters)', 'status' => 1, 'sort_order' => 24],

        // ── Faculty of Humanities ──────────────────────────────────────
        ['section_key' => 'programme_catalog_humanities', 'item_type' => 'programme', 'title' => 'Bachelor of Arts in Journalism and Media Studies (BAJM)', 'subtitle' => "Bachelor's Degree", 'content' => '3 Academic Years (6 Semesters)', 'status' => 1, 'sort_order' => 1],
        ['section_key' => 'programme_catalog_humanities', 'item_type' => 'programme', 'title' => 'Bachelor of Social Work and Social Administration (BSWSA)', 'subtitle' => "Bachelor's Degree", 'content' => '3 Academic Years (6 Semesters)', 'status' => 1, 'sort_order' => 2],
        ['section_key' => 'programme_catalog_humanities', 'item_type' => 'programme', 'title' => 'Diploma in Journalism (DJ)', 'subtitle' => 'Diploma', 'content' => '2 Academic Years (4 Semesters)', 'status' => 1, 'sort_order' => 3],
        ['section_key' => 'programme_catalog_humanities', 'item_type' => 'programme', 'title' => 'Diploma in Social Work and Social Administration (DSWSA)', 'subtitle' => 'Diploma', 'content' => '2 Academic Years (4 Semesters)', 'status' => 1, 'sort_order' => 4],
        ['section_key' => 'programme_catalog_humanities', 'item_type' => 'programme', 'title' => 'National Certificate in Creative and Performing Arts (NCCPA)', 'subtitle' => 'National Certificate', 'content' => '2 Academic Years (4 Semesters)', 'status' => 1, 'sort_order' => 5],
        ['section_key' => 'programme_catalog_humanities', 'item_type' => 'programme', 'title' => 'National Certificate in Guidance and Counseling (NCGC)', 'subtitle' => 'National Certificate', 'content' => '2 Academic Years (4 Semesters)', 'status' => 1, 'sort_order' => 6],
        ['section_key' => 'programme_catalog_humanities', 'item_type' => 'programme', 'title' => 'National Certificate in Journalism and Media Studies (NCJMS)', 'subtitle' => 'National Certificate', 'content' => '2 Academic Years (4 Semesters)', 'status' => 1, 'sort_order' => 7],
        ['section_key' => 'programme_catalog_humanities', 'item_type' => 'programme', 'title' => 'National Certificate in Library and Information Science (NCLIS)', 'subtitle' => 'National Certificate', 'content' => '2 Academic Years (4 Semesters)', 'status' => 1, 'sort_order' => 8],
        ['section_key' => 'programme_catalog_humanities', 'item_type' => 'programme', 'title' => 'National Certificate in Social Work and Social Administration (NCSWSA)', 'subtitle' => 'National Certificate', 'content' => '2 Academic Years (4 Semesters)', 'status' => 1, 'sort_order' => 9],

        // ── Faculty of Education ────────────────────────────────────────
        ['section_key' => 'programme_catalog_education', 'item_type' => 'programme', 'title' => 'Bachelor of Arts with Education (Secondary) (BAE)', 'subtitle' => "Bachelor's Degree", 'content' => '3 Academic Years (6 Semesters)', 'status' => 1, 'sort_order' => 1],
        ['section_key' => 'programme_catalog_education', 'item_type' => 'programme', 'title' => 'Bachelor of Business Studies with Education (BBSE)', 'subtitle' => "Bachelor's Degree", 'content' => '3 Academic Years (6 Semesters)', 'status' => 1, 'sort_order' => 2],
        ['section_key' => 'programme_catalog_education', 'item_type' => 'programme', 'title' => 'Bachelor of Education (Primary) (BEP)', 'subtitle' => "Bachelor's Degree", 'content' => '3 Academic Years (6 Semesters)', 'status' => 1, 'sort_order' => 3],
        ['section_key' => 'programme_catalog_education', 'item_type' => 'programme', 'title' => 'Bachelor of Early Childhood Care and Education (BECCE)', 'subtitle' => "Bachelor's Degree", 'content' => '3 Academic Years (6 Semesters)', 'status' => 1, 'sort_order' => 4],
        ['section_key' => 'programme_catalog_education', 'item_type' => 'programme', 'title' => 'Bachelor of Science with Education (BSE)', 'subtitle' => "Bachelor's Degree", 'content' => '3 Academic Years (6 Semesters)', 'status' => 1, 'sort_order' => 5],
        ['section_key' => 'programme_catalog_education', 'item_type' => 'programme', 'title' => 'Diploma in Education (Primary) (DEP)', 'subtitle' => 'Diploma', 'content' => '2 Academic Years (4 Semesters)', 'status' => 1, 'sort_order' => 6],
        ['section_key' => 'programme_catalog_education', 'item_type' => 'programme', 'title' => 'Diploma in Early Childhood Care and Education (DECCE)', 'subtitle' => 'Diploma', 'content' => '2 Academic Years (4 Semesters)', 'status' => 1, 'sort_order' => 7],
        ['section_key' => 'programme_catalog_education', 'item_type' => 'programme', 'title' => 'Higher Education Certificate (Humanities)', 'subtitle' => 'Bridging Programme', 'content' => '1 Academic Year', 'status' => 1, 'sort_order' => 8],
        ['section_key' => 'programme_catalog_education', 'item_type' => 'programme', 'title' => 'Higher Education Certificate (Biological Sciences)', 'subtitle' => 'Bridging Programme', 'content' => '1 Academic Year', 'status' => 1, 'sort_order' => 9],
        ['section_key' => 'programme_catalog_education', 'item_type' => 'programme', 'title' => 'Higher Education Certificate (Physical Sciences)', 'subtitle' => 'Bridging Programme', 'content' => '1 Academic Year', 'status' => 1, 'sort_order' => 10],
        ['section_key' => 'programme_catalog_education', 'item_type' => 'programme', 'title' => 'Certificate in Nursery Teaching (CNT)', 'subtitle' => 'Certificate', 'content' => '2 Academic Years (4 Semesters)', 'status' => 1, 'sort_order' => 11],
        ['section_key' => 'programme_catalog_education', 'item_type' => 'programme', 'title' => 'Certificate in Early Childhood Care and Education (CECE)', 'subtitle' => 'Certificate', 'content' => '2 Academic Years (4 Semesters)', 'status' => 1, 'sort_order' => 12],
        ['section_key' => 'programme_catalog_education', 'item_type' => 'programme', 'title' => 'National Certificate in Guidance and Counseling (NCGC)', 'subtitle' => 'National Certificate', 'content' => '2 Academic Years (4 Semesters)', 'status' => 1, 'sort_order' => 13],

        [
            'section_key' => 'admissions',
            'item_type' => 'step',
            'title' => 'Select your programme',
            'description' => 'Visit the PIIE online admissions portal and select your desired programme.',
            'status' => 1,
            'sort_order' => 1,
        ],
        [
            'section_key' => 'admissions',
            'item_type' => 'step',
            'title' => 'Complete the application form',
            'description' => 'Fill in your personal, educational, and professional details online.',
            'status' => 1,
            'sort_order' => 2,
        ],
        [
            'section_key' => 'admissions',
            'item_type' => 'step',
            'title' => 'Upload your documents',
            'description' => 'Certified copies of your academic certificates and transcripts, a valid national ID or passport, and a recent passport-size photograph.',
            'status' => 1,
            'sort_order' => 3,
        ],
        [
            'section_key' => 'admissions',
            'item_type' => 'step',
            'title' => 'Pay the application fee',
            'description' => 'Pay the non-refundable application fee through the secure online payment portal.',
            'status' => 1,
            'sort_order' => 4,
        ],
        [
            'section_key' => 'admissions',
            'item_type' => 'step',
            'title' => 'Submit your application',
            'description' => 'Receive an automated confirmation with a unique application reference number.',
            'status' => 1,
            'sort_order' => 5,
        ],
        [
            'section_key' => 'admissions',
            'item_type' => 'step',
            'title' => 'Await the admissions decision',
            'description' => "The Admissions Committee's decision is communicated by official email within ten working days of a complete application.",
            'status' => 1,
            'sort_order' => 6,
        ],
        [
            'section_key' => 'admissions',
            'item_type' => 'step',
            'title' => 'Complete your registration',
            'description' => 'Upon admission, pay your first semester tuition fee and activate your student account.',
            'status' => 1,
            'sort_order' => 7,
        ],
        [
            'section_key' => 'entry_requirements',
            'item_type' => 'requirement',
            'title' => "Masters Degree & Postgraduate Diploma",
            'subtitle' => 'Postgraduate',
            'description' => "A Bachelor's Degree from a recognised and accredited university in a relevant or related discipline.\nHolders of a relevant Postgraduate Diploma may be considered for direct admission into Year Two of a Masters programme, subject to credit transfer evaluation.\nA minimum of two years of relevant professional experience is recommended, though not mandatory for all programmes.",
            'status' => 1,
            'sort_order' => 1,
        ],
        [
            'section_key' => 'entry_requirements',
            'item_type' => 'requirement',
            'title' => "Bachelor's Degree",
            'subtitle' => 'Undergraduate',
            'description' => "Uganda Advanced Certificate of Education (UACE) with at least two principal passes and one subsidiary pass, or a recognised equivalent from an international examining body.\nInternational students without A Level qualifications must first complete the PIIE Higher Education Certificate (HEC).\nHolders of a relevant Diploma may apply for direct admission into Year Two, subject to credit transfer evaluation.",
            'status' => 1,
            'sort_order' => 2,
        ],
        [
            'section_key' => 'entry_requirements',
            'item_type' => 'requirement',
            'title' => 'Diploma',
            'subtitle' => 'Undergraduate',
            'description' => "UACE with at least one principal pass and one subsidiary pass.\nOr the PIIE Higher Education Certificate (HEC) or an equivalent recognised bridging qualification.",
            'status' => 1,
            'sort_order' => 3,
        ],
        [
            'section_key' => 'entry_requirements',
            'item_type' => 'requirement',
            'title' => 'Certificate',
            'subtitle' => 'Entry Level',
            'description' => "Uganda Certificate of Education (UCE) with at least five passes, including English Language and Mathematics.\nOr a recognised equivalent secondary school leaving certificate from an accredited institution.",
            'status' => 1,
            'sort_order' => 4,
        ],
        [
            'section_key' => 'entry_requirements',
            'item_type' => 'requirement',
            'title' => 'Higher Education Certificate (Bridging)',
            'subtitle' => 'Bridging',
            'description' => "A subsidiary pass in a principal subject at UACE or equivalent.\nOr, for international students without an A Level qualification, a recognised equivalent secondary education qualification.",
            'status' => 1,
            'sort_order' => 5,
        ],
        [
            'section_key' => 'entry_requirements',
            'item_type' => 'requirement',
            'title' => 'Credit Transfer Policy',
            'subtitle' => 'All Levels',
            'description' => "Holders of a relevant Postgraduate Diploma are eligible for admission into Semester Three (Year Two) of an applicable Masters programme.\nHolders of a relevant Diploma are eligible for admission into Semester Three (Year Two) of a related Bachelor's Degree programme.\nAll credit transfer applications are evaluated individually by the PIIE Credit Transfer and Admissions Committee.",
            'status' => 1,
            'sort_order' => 6,
        ],
        [
            'section_key' => 'leadership_team',
            'item_type' => 'leader',
            'title' => 'Twinamatsiko Naboth, PhD.c',
            'subtitle' => 'Director',
            'description' => 'Provides overall institutional leadership, strategic direction, and external partnership stewardship for PIIE.',
            'status' => 1,
            'sort_order' => 1,
        ],
        [
            'section_key' => 'leadership_team',
            'item_type' => 'leader',
            'title' => 'Nyamurungi Naome',
            'subtitle' => 'Principal',
            'description' => 'Leads academic quality, programme integrity, curriculum oversight, and the broader academic culture of the institution.',
            'status' => 1,
            'sort_order' => 2,
        ],
        [
            'section_key' => 'leadership_team',
            'item_type' => 'leader',
            'title' => 'Academic Registrar',
            'subtitle' => 'Academic Registrar',
            'description' => 'Oversees admissions, academic records, examinations administration, and certification processes.',
            'status' => 1,
            'sort_order' => 3,
        ],
        [
            'section_key' => 'leadership_team',
            'item_type' => 'leader',
            'title' => 'Institute Secretary',
            'subtitle' => 'Institute Secretary',
            'description' => 'Coordinates governance, compliance, official records management, and administrative operations.',
            'status' => 1,
            'sort_order' => 4,
        ],
        [
            'section_key' => 'welcome_messages',
            'item_type' => 'message',
            'title' => 'Welcome Message from the Director',
            'subtitle' => 'Twinamatsiko Naboth, PhD.c',
            'description' => 'PIIE was built as a deliberate commitment to delivering the highest quality education to every learner regardless of location.',
            'content' => 'A PIIE qualification is an investment in yourself that will generate returns for the rest of your professional life.',
            'status' => 1,
            'sort_order' => 1,
        ],
        [
            'section_key' => 'welcome_messages',
            'item_type' => 'message',
            'title' => 'Welcome Message from the Principal',
            'subtitle' => 'Nyamurungi Naome',
            'description' => 'Academic excellence is built through deliberate programme design, engaged faculty, rigorous assessment, and learner-centred planning.',
            'content' => 'Approach your studies at PIIE with commitment, curiosity, and courage. We are here to challenge and support you.',
            'status' => 1,
            'sort_order' => 2,
        ],
        [
            'section_key' => 'welcome_messages',
            'item_type' => 'message',
            'title' => 'Welcome Message from the Academic Registrar',
            'subtitle' => 'Office of the Academic Registrar',
            'description' => 'Academic integrity, efficient records management, transparent admissions, and reliable certification are central to the learner experience.',
            'content' => 'Your academic records are protected, your credentials are secure, and your progress is managed with diligence and care.',
            'status' => 1,
            'sort_order' => 3,
        ],
        [
            'section_key' => 'welcome_messages',
            'item_type' => 'message',
            'title' => 'Welcome Message from the Institute Secretary',
            'subtitle' => 'Office of the Institute Secretary',
            'description' => 'Strong governance, compliance, and administrative transparency are treated as prerequisites for lasting academic quality.',
            'content' => 'We welcome scrutiny, engagement, and partnership as PIIE builds a strong and credible institutional foundation.',
            'status' => 1,
            'sort_order' => 4,
        ],
        [
            'section_key' => 'partnerships_affiliations',
            'item_type' => 'partner',
            'title' => 'Team University, Kampala, Uganda',
            'description' => 'Academic partnership for programme delivery, validation, and qualification recognition.',
            'status' => 1,
            'sort_order' => 1,
        ],
        [
            'section_key' => 'partnerships_affiliations',
            'item_type' => 'partner',
            'title' => 'Equity Group Holdings Uganda',
            'description' => 'Student financial inclusion and educational financing support.',
            'status' => 1,
            'sort_order' => 2,
        ],
        [
            'section_key' => 'partnerships_affiliations',
            'item_type' => 'partner',
            'title' => 'SurePay Limited',
            'description' => 'Technology partnership for secure and seamless online payments.',
            'status' => 1,
            'sort_order' => 3,
        ],
        [
            'section_key' => 'partnerships_affiliations',
            'item_type' => 'partner',
            'title' => 'Uganda Vocational Training and Apprenticeship Board (UVTAB)',
            'description' => 'Alignment with national skills and qualifications frameworks.',
            'status' => 1,
            'sort_order' => 4,
        ],
        [
            'section_key' => 'partnerships_affiliations',
            'item_type' => 'partner',
            'title' => 'Ministry of Education and Sports, Uganda',
            'description' => 'Regulatory compliance within Uganda\'s higher education framework.',
            'status' => 1,
            'sort_order' => 5,
        ],
        [
            'section_key' => 'partnerships_affiliations',
            'item_type' => 'partner',
            'title' => 'Uganda Registration Services Bureau (URSB)',
            'description' => 'Institutional legal registration and compliance.',
            'status' => 1,
            'sort_order' => 6,
        ],
        [
            'section_key' => 'faqs',
            'item_type' => 'faq',
            'title' => 'What is Prime International Institute of Excellence (PIIE)?',
            'description' => 'PIIE is a modern higher education institution established in Uganda in 2026, committed to internationally benchmarked programmes from Certificate to Masters level through the ODeL model.',
            'status' => 1,
            'sort_order' => 1,
        ],
        [
            'section_key' => 'faqs',
            'item_type' => 'faq',
            'title' => 'Is PIIE a recognised institution?',
            'description' => 'PIIE operates within Uganda\'s higher education regulatory framework and its programmes are validated in partnership with accredited universities.',
            'status' => 1,
            'sort_order' => 2,
        ],
        [
            'section_key' => 'faqs',
            'item_type' => 'faq',
            'title' => 'How are PIIE programmes delivered?',
            'description' => 'All programmes are delivered entirely online through the ODeL model using the PIIE Learning Management System and related digital academic platforms.',
            'status' => 1,
            'sort_order' => 3,
        ],
        [
            'section_key' => 'faqs',
            'item_type' => 'faq',
            'title' => 'Can I transfer credits from a previous qualification?',
            'description' => 'Yes. Relevant postgraduate diploma and diploma holders may qualify for advanced standing subject to individual assessment by the PIIE Credit Transfer and Admissions Committee.',
            'status' => 1,
            'sort_order' => 4,
        ],
        [
            'section_key' => 'faqs',
            'item_type' => 'faq',
            'title' => 'Is the ODeL model suitable for working professionals?',
            'description' => 'Yes. The model is specifically designed for working professionals with 24/7 access to materials, recorded live sessions, and flexible study planning.',
            'status' => 1,
            'sort_order' => 5,
        ],
        [
            'section_key' => 'faqs',
            'item_type' => 'faq',
            'title' => 'Where is PIIE located?',
            'description' => 'PIIE is headquartered in Nansana Municipality, Wakiso District, Uganda, while serving learners nationally and internationally through fully online delivery.',
            'status' => 1,
            'sort_order' => 6,
        ],
        [
            'section_key' => 'faqs',
            'item_type' => 'faq',
            'title' => 'What are the tuition fees at PIIE?',
            'description' => 'Masters and Postgraduate Diploma programmes cost UGX 1,200,000 per semester; Bachelor\'s Degree programmes cost UGX 1,000,000 per semester; Diploma programmes cost UGX 650,000 per semester; and Certificate programmes cost UGX 600,000 per semester. Fees are reviewed periodically — confirm current rates with the Admissions Office.',
            'status' => 1,
            'sort_order' => 7,
        ],
        [
            'section_key' => 'faqs',
            'item_type' => 'faq',
            'title' => 'Are there flexible payment arrangements?',
            'description' => 'Yes. The PIIE Finance Office provides guidance on instalment-based payment plans for students who are unable to pay their full semester fees at once. Fees are payable online via mobile money, bank transfer, or debit/credit card.',
            'status' => 1,
            'sort_order' => 8,
        ],
        [
            'section_key' => 'faqs',
            'item_type' => 'faq',
            'title' => 'What qualification will I receive upon graduation?',
            'description' => 'A formal Degree, Diploma, or Certificate under the PIIE academic framework, validated in partnership with the relevant accredited partner university. The awarding institution for each specific programme is communicated at the time of admission.',
            'status' => 1,
            'sort_order' => 9,
        ],
        [
            'section_key' => 'faqs',
            'item_type' => 'faq',
            'title' => 'Is PIIE the same institution as Divine Open Institute of Management?',
            'description' => 'No. PIIE and Divine Open Institute of Management (DOIM) are separate and distinct institutions that happen to operate under the same institutional leadership. Each has its own identity, academic structure, programme portfolio, governance, and operational profile.',
            'status' => 1,
            'sort_order' => 10,
        ],
        [
            'section_key' => 'quick_links',
            'item_type' => 'quick_link',
            'title' => 'Home',
            'link' => '#home',
            'status' => 1,
            'sort_order' => 1,
        ],
        [
            'section_key' => 'quick_links',
            'item_type' => 'quick_link',
            'title' => 'About',
            'link' => '#about',
            'status' => 1,
            'sort_order' => 2,
        ],
        [
            'section_key' => 'quick_links',
            'item_type' => 'quick_link',
            'title' => 'Programmes',
            'link' => '#programs',
            'status' => 1,
            'sort_order' => 3,
        ],
        [
            'section_key' => 'quick_links',
            'item_type' => 'quick_link',
            'title' => 'Admissions',
            'link' => '#admissions',
            'status' => 1,
            'sort_order' => 4,
        ],
        [
            'section_key' => 'quick_links',
            'item_type' => 'quick_link',
            'title' => 'Research',
            'link' => '#research_innovation',
            'status' => 1,
            'sort_order' => 5,
        ],
        [
            'section_key' => 'quick_links',
            'item_type' => 'quick_link',
            'title' => 'Contact',
            'link' => '#contact',
            'status' => 1,
            'sort_order' => 6,
        ],
        [
            'section_key' => 'portals_links',
            'item_type' => 'portal',
            'title' => 'Online Admissions Portal',
            'link' => '#admissions',
            'status' => 1,
            'sort_order' => 1,
        ],
        [
            'section_key' => 'portals_links',
            'item_type' => 'portal',
            'title' => 'Student Portal',
            'link' => '/login',
            'status' => 1,
            'sort_order' => 2,
        ],
        [
            'section_key' => 'portals_links',
            'item_type' => 'portal',
            'title' => 'Learning Management System',
            'link' => '/login',
            'status' => 1,
            'sort_order' => 3,
        ],
        [
            'section_key' => 'social_media_links',
            'item_type' => 'social',
            'title' => 'Facebook',
            'link' => '#',
            'status' => 1,
            'sort_order' => 1,
        ],
        [
            'section_key' => 'social_media_links',
            'item_type' => 'social',
            'title' => 'LinkedIn',
            'link' => '#',
            'status' => 1,
            'sort_order' => 2,
        ],
        [
            'section_key' => 'social_media_links',
            'item_type' => 'social',
            'title' => 'YouTube',
            'link' => '#',
            'status' => 1,
            'sort_order' => 3,
        ],
        [
            'section_key' => 'social_media_links',
            'item_type' => 'social',
            'title' => 'Instagram',
            'link' => '#',
            'status' => 1,
            'sort_order' => 4,
        ],
    ],
    'settings' => [
        'institution_name' => 'Prime International Institute of Excellence (PIIE)',
        'tagline' => 'Internationally Benchmarked Education for Global Excellence',
        'motto' => 'Strive. Excel. Lead.',
        'contact_address' => 'Nansana Municipality, Wakiso District, Uganda',
        'director_name' => 'Twinamatsiko Naboth, PhD.c',
        'principal_name' => 'Nyamurungi Naome',
        'academic_registrar_name' => 'Academic Registrar',
        'institute_secretary_name' => 'Institute Secretary',
        'footer_copyright' => '© Prime International Institute of Excellence (PIIE). All Rights Reserved.',
        'hero_badge' => 'Open, Distance and e-Learning (ODeL)',
        'program_delivery_label' => 'FULLY ONLINE / ODeL',
    ],
];