<?php

return [
    'pages' => [
        [
            'page_key' => 'home',
            'title' => 'Home',
            'slug' => 'home',
            'status' => 1,
            'sort_order' => 1,
            'subtitle' => 'Internationally Benchmarked Education for Global Excellence',
            'display_order' => 1,
            'show_in_navigation' => 1,
            'cta_button_text' => 'Apply Now',
            'cta_button_link' => 'admissions',
        ],
        [
            'page_key' => 'about',
            'title' => 'About Us',
            'slug' => 'about-us',
            'status' => 1,
            'sort_order' => 2,
            'subtitle' => 'Our History, Values, and Institutional Direction',
            'display_order' => 2,
            'show_in_navigation' => 1,
        ],
        [
            'page_key' => 'programs',
            'title' => 'Academic Programmes',
            'slug' => 'academic-programmes',
            'status' => 1,
            'sort_order' => 3,
            'subtitle' => 'Programme Levels, Delivery Model, and Student Experience',
            'display_order' => 3,
            'show_in_navigation' => 1,
        ],
        [
            'page_key' => 'admissions',
            'title' => 'Admissions',
            'slug' => 'admissions',
            'status' => 1,
            'sort_order' => 4,
            'subtitle' => 'Entry Requirements, Application Steps, and Credit Transfer',
            'display_order' => 4,
            'show_in_navigation' => 1,
            'cta_button_text' => 'Begin Application',
            'cta_button_link' => 'contact-us',
        ],
        [
            'page_key' => 'research',
            'title' => 'Research & Innovation',
            'slug' => 'research-and-innovation',
            'status' => 1,
            'sort_order' => 5,
            'subtitle' => 'Knowledge Creation, Partnerships, and Institutional Impact',
            'display_order' => 5,
            'show_in_navigation' => 1,
        ],
        [
            'page_key' => 'contact',
            'title' => 'Contact Us',
            'slug' => 'contact-us',
            'status' => 1,
            'sort_order' => 6,
            'subtitle' => 'Official Communication Channels and Enquiries',
            'display_order' => 6,
            'show_in_navigation' => 1,
        ],
    ],
    'sections' => [
        [
            'page_key' => 'home',
            'section_key' => 'hero_slider',
            'title' => 'Prime International Institute of Excellence (PIIE)',
            'subtitle' => 'A modern higher education institution established in Uganda for flexible, technology-enabled learning of genuine international standard.',
            'content' => 'Prime International Institute of Excellence serves ambitious learners across Uganda, East Africa, and the wider world through rigorous academic programmes, professional relevance, and accessible Open, Distance and e-Learning.',
            'status' => 1,
            'sort_order' => 1,
        ],
        [
            'page_key' => 'about',
            'section_key' => 'about_institution',
            'title' => 'About Us',
            'subtitle' => 'Prime International Institute of Excellence (PIIE)',
            'content' => "Prime International Institute of Excellence (PIIE) is a modern higher education institution established in Uganda with a clear mandate: to deliver academic programmes of genuine international standard through flexible, technology-enabled learning that is accessible to ambitious learners across Uganda, East Africa, and the wider world.\n\nPIIE was founded on the conviction that academic excellence and professional relevance are complementary dimensions of a single educational mission. Every programme we offer, every faculty member we engage, and every student we admit reflects this conviction.",
            'status' => 1,
            'sort_order' => 2,
        ],
        [
            'page_key' => 'about',
            'section_key' => 'origin_history',
            'title' => 'Origin and History',
            'subtitle' => 'The Founding of PIIE',
            'content' => "Prime International Institute of Excellence was founded in 2026 by academic and institutional leaders responding to a gap in Uganda's higher education landscape: the shortage of institutions combining genuine academic rigour, flexible delivery models, and an explicitly international orientation.\n\nFrom its headquarters in Nansana Municipality, Wakiso District, Uganda, PIIE has grown in student enrolment, academic staff capacity, programme portfolio, and institutional partnerships while ensuring that geography is never a barrier to academic achievement.",
            'status' => 1,
            'sort_order' => 3,
        ],
        [
            'page_key' => 'about',
            'section_key' => 'institutional_character',
            'title' => 'Institutional Character',
            'subtitle' => 'What Distinguishes PIIE',
            'content' => "PIIE is defined by uncompromising academic standards, international orientation, technology-driven learning, a strong career and leadership focus, and inclusive excellence. Assessments are rigorous, programmes are benchmarked against international standards, and every learner is prepared to compete and lead in a globalised world.",
            'status' => 1,
            'sort_order' => 4,
        ],
        [
            'page_key' => 'about',
            'section_key' => 'vision_mission_motto',
            'title' => 'Vision, Mission, and Motto',
            'subtitle' => 'The Institutional Direction of PIIE',
            'content' => "Vision: To be a premier internationally recognised institution of academic excellence, shaping transformational leaders, innovators, entrepreneurs, and globally competitive professionals who drive sustainable development across Africa and the wider world.\n\nMission: To deliver rigorous, innovative, and internationally benchmarked academic programmes through flexible, technology-enabled learning systems that equip learners with the knowledge, skills, ethical values, and leadership capabilities required for professional excellence, entrepreneurial success, and meaningful contribution to society in a rapidly evolving global economy.\n\nMotto: Strive. Excel. Lead.",
            'status' => 1,
            'sort_order' => 5,
        ],
        [
            'page_key' => 'about',
            'section_key' => 'core_values',
            'title' => 'Core Values',
            'subtitle' => 'The Standards That Govern the Institution',
            'content' => "Excellence, Integrity, Innovation, Global Competitiveness, Entrepreneurial Spirit, Inclusivity, and Accountability define all academic, administrative, and stakeholder engagements at PIIE. These values shape programme quality, student support, governance, and the credibility of every qualification we award.",
            'status' => 1,
            'sort_order' => 6,
        ],
        [
            'page_key' => 'about',
            'section_key' => 'educational_philosophy',
            'title' => 'Institutional Philosophy',
            'subtitle' => 'Our Philosophy of Education',
            'content' => "At PIIE, higher education serves four interconnected purposes: the development of intellectual capacity, the cultivation of professional competence, the formation of ethical character, and the preparation of individuals for meaningful participation in society.\n\nWe believe education is not the accumulation of information but the transformation of a person's capacity to understand, reason, create, and lead. We also believe that rigour and flexibility are not opposites. PIIE was built to demonstrate that the highest academic standards can coexist with the digital accessibility modern learners require.",
            'status' => 1,
            'sort_order' => 7,
        ],
        [
            'page_key' => 'about',
            'section_key' => 'why_choose_us',
            'title' => 'Why Choose PIIE',
            'subtitle' => 'Why Ambitious Learners Choose PIIE',
            'content' => "PIIE offers internationally benchmarked programmes, flexible ODeL delivery without compromising quality, qualifications validated by recognised partner universities, experienced postgraduate-credentialed faculty, a complete digital academic experience, affordable and transparent fees, credit transfer pathways, leadership and entrepreneurship development, and personalised support from enrolment to graduation.",
            'status' => 1,
            'sort_order' => 8,
        ],
        [
            'page_key' => 'about',
            'section_key' => 'welcome_messages',
            'title' => 'Welcome Messages',
            'subtitle' => 'Leadership Perspectives',
            'content' => 'PIIE leadership welcomes students, partners, employers, alumni, and stakeholders with a shared commitment to quality, integrity, and long-term learner impact.',
            'status' => 1,
            'sort_order' => 9,
        ],
        [
            'page_key' => 'about',
            'section_key' => 'leadership_team',
            'title' => 'Leadership Team',
            'subtitle' => 'Institutional Leadership',
            'content' => 'The leadership of PIIE provides academic direction, governance oversight, student records stewardship, and institutional administration grounded in excellence and accountability.',
            'status' => 1,
            'sort_order' => 10,
        ],
        [
            'page_key' => 'about',
            'section_key' => 'governance_structure',
            'title' => 'Governance Structure',
            'subtitle' => 'Formal and Transparent Institutional Governance',
            'content' => "Prime International Institute of Excellence is governed by a formal structure composed of the Governing Council, the Director, the Principal, the Academic Registrar, and the Institute Secretary. This framework ensures accountability, academic quality, regulatory compliance, and the long-term integrity of the institution.",
            'status' => 1,
            'sort_order' => 11,
        ],
        [
            'page_key' => 'about',
            'section_key' => 'strategic_plan',
            'title' => 'Strategic Plan (2026 - 2033)',
            'subtitle' => 'Our Strategic Direction',
            'content' => "PIIE's seven-year strategic framework is built around six objectives: academic excellence and programme quality; research, knowledge creation, and innovation; strategic partnerships and institutional networks; technology, digital infrastructure, and learning innovation; institutional sustainability and governance excellence; and student success, graduate impact, and community engagement.",
            'status' => 1,
            'sort_order' => 12,
        ],
        [
            'page_key' => 'programs',
            'section_key' => 'academic_programmes',
            'title' => 'Academic Programmes',
            'subtitle' => 'Programme Levels, Durations, and Fees',
            'content' => "PIIE offers a carefully designed portfolio of academic programmes from Certificate to Masters Degree. All programmes are delivered through the Open, Distance and e-Learning model, combining robust theoretical foundations with practical real-world application.\n\nMasters Degree Programmes: 2 Academic Years (4 Semesters) - UGX 1,200,000 per Semester.\nPostgraduate Diploma Programmes: 1 Academic Year (2 Semesters) - UGX 1,200,000 per Semester.\nBachelor's Degree Programmes: 3 Academic Years (6 Semesters) - UGX 1,000,000 per Semester.\nDiploma Programmes: 2 Academic Years (4 Semesters) - UGX 650,000 per Semester.\nCertificate Programmes: 2 Academic Years (4 Semesters) - UGX 600,000 per Semester.",
            'status' => 1,
            'sort_order' => 13,
        ],
        [
            'page_key' => 'programs',
            'section_key' => 'programme_categories',
            'title' => 'Programme Categories',
            'subtitle' => 'Study Pathways at PIIE',
            'content' => 'Choose the study level that matches your qualifications, professional stage, and long-term ambition.',
            'status' => 1,
            'sort_order' => 14,
        ],
        [
            'page_key' => 'admissions',
            'section_key' => 'admissions',
            'title' => 'Admissions',
            'subtitle' => 'Accessible, Merit-Based, and Fully Digital',
            'content' => "PIIE welcomes learners from diverse educational, professional, and personal backgrounds. Applications are completed digitally through the admissions portal. Applicants select a programme, complete the form, upload certified documents, pay the application fee, submit, and receive a decision within ten working days of a complete application.\n\nPIIE also operates a formal credit transfer policy for relevant postgraduate diploma and diploma holders seeking advanced standing.",
            'status' => 1,
            'sort_order' => 15,
        ],
        [
            'page_key' => 'programs',
            'section_key' => 'online_learning_odel',
            'title' => 'Online and Distance Learning',
            'subtitle' => 'Learn from Anywhere. Achieve Without Limits.',
            'content' => "PIIE operates exclusively through the Open, Distance and e-Learning model. Students study entirely online, access course materials through the Learning Management System, engage with faculty through live virtual sessions and moderated forums, submit assignments digitally, and sit examinations through secure platforms.\n\nThe ODeL model is structured around self-directed study, facilitated sessions, continuous assessment, end-of-semester examinations, and responsive faculty support.",
            'status' => 1,
            'sort_order' => 16,
        ],
        [
            'page_key' => 'research',
            'section_key' => 'research_innovation',
            'title' => 'Research and Innovation',
            'subtitle' => 'Research. Knowledge. Impact.',
            'content' => "Research is central to PIIE's academic mission. The Research and Innovation Centre coordinates original knowledge creation, policy-relevant inquiry, collaborative projects, innovation initiatives, publications, and dissemination across business, public administration, governance, technology, entrepreneurship, finance, higher education, and sustainable development.",
            'status' => 1,
            'sort_order' => 17,
        ],
        [
            'page_key' => 'research',
            'section_key' => 'partnerships_affiliations',
            'title' => 'Partnerships and Collaborations',
            'subtitle' => 'Building Excellence Through Strategic Alliances',
            'content' => "PIIE builds strategic alliances with universities, industry leaders, financial institutions, government agencies, and regulatory bodies that strengthen programme quality, student opportunity, and institutional credibility. Each partnership is evaluated against one test: whether it improves the learner experience and the standing of PIIE qualifications.",
            'status' => 1,
            'sort_order' => 18,
        ],
        [
            'page_key' => 'programs',
            'section_key' => 'student_support_services',
            'title' => 'Student Support Services',
            'subtitle' => 'Your Success is Our Institutional Priority',
            'content' => "PIIE provides academic advising, digital library access, technical and ICT support, career development services, personal counselling and wellness support, financial guidance, alumni mentorship, examination guidance, and dedicated international student support. The student journey is supported from enrolment to graduation and beyond.",
            'status' => 1,
            'sort_order' => 19,
        ],
        [
            'page_key' => 'programs',
            'section_key' => 'international_students',
            'title' => 'International Students',
            'subtitle' => 'A World-Class Institution. Open to the World.',
            'content' => "PIIE welcomes students from across the globe through a fully online delivery model that eliminates relocation requirements while preserving academic rigour. International students benefit from validated qualifications, English-language delivery, affordable fees, global classroom perspectives, and dedicated orientation and advisory support.",
            'status' => 1,
            'sort_order' => 20,
        ],
        [
            'page_key' => 'research',
            'section_key' => 'news_events',
            'title' => 'News and Events',
            'subtitle' => 'Stay Informed. Stay Connected. Stay Ahead.',
            'content' => "The PIIE News and Events page is the central source for institutional announcements, academic highlights, programme updates, partnership news, student achievements, and upcoming events including virtual open days, seminars, conferences, and professional development workshops.",
            'status' => 1,
            'sort_order' => 21,
        ],
        [
            'page_key' => 'admissions',
            'section_key' => 'faqs',
            'title' => 'Frequently Asked Questions',
            'subtitle' => 'Common Questions About PIIE',
            'content' => 'Below are clear answers to common questions from prospective students, enrolled learners, alumni, partners, and other stakeholders.',
            'status' => 1,
            'sort_order' => 22,
        ],
        [
            'page_key' => 'contact',
            'section_key' => 'contact_page',
            'title' => 'Official Communication Channels',
            'subtitle' => 'Consistent Public Contact Information',
            'content' => "Institution Name: Prime International Institute of Excellence. Acronym: PIIE. Headquarters: Nansana Municipality, Wakiso District, Uganda. Office Hours: Monday to Friday and Saturday by official schedule. Sunday and Public Holidays: Closed, while digital enquiries remain accepted and are responded to on the next working day.\n\nThe admissions portal, Learning Management System, and student portal remain accessible twenty-four hours a day, seven days a week.",
            'status' => 1,
            'sort_order' => 23,
        ],
        [
            'page_key' => 'home',
            'section_key' => 'footer_settings',
            'title' => 'Footer',
            'subtitle' => 'Footer information and quick navigation',
            'content' => 'Footer content and official links for Prime International Institute of Excellence.',
            'status' => 1,
            'sort_order' => 24,
        ],
        [
            'page_key' => 'home',
            'section_key' => 'quick_links',
            'title' => 'Quick Links',
            'subtitle' => 'Primary website navigation',
            'content' => 'Shortcut links to key pages and information categories.',
            'status' => 1,
            'sort_order' => 25,
        ],
        [
            'page_key' => 'home',
            'section_key' => 'portals_links',
            'title' => 'Portals Links',
            'subtitle' => 'Admissions and digital portals',
            'content' => 'Access the admissions portal, student systems, and institutional communication channels.',
            'status' => 1,
            'sort_order' => 26,
        ],
        [
            'page_key' => 'home',
            'section_key' => 'social_media_links',
            'title' => 'Social Media Links',
            'subtitle' => 'Official social and digital channels',
            'content' => 'Official social links can be updated here as institutional channels are confirmed.',
            'status' => 1,
            'sort_order' => 27,
        ],
    ],
    'items' => [
        [
            'section_key' => 'programme_categories',
            'item_type' => 'program_category',
            'title' => 'Masters Degree Programmes',
            'subtitle' => '2 Academic Years (4 Semesters)',
            'description' => 'Advanced postgraduate study designed for leadership, professional growth, and global competitiveness.',
            'content' => 'UGX 1,200,000 per semester',
            'status' => 1,
            'sort_order' => 1,
        ],
        [
            'section_key' => 'programme_categories',
            'item_type' => 'program_category',
            'title' => 'Postgraduate Diploma Programmes',
            'subtitle' => '1 Academic Year (2 Semesters)',
            'description' => 'Focused postgraduate pathways for specialised professional advancement and academic progression.',
            'content' => 'UGX 1,200,000 per semester',
            'status' => 1,
            'sort_order' => 2,
        ],
        [
            'section_key' => 'programme_categories',
            'item_type' => 'program_category',
            'title' => 'Bachelor\'s Degree Programmes',
            'subtitle' => '3 Academic Years (6 Semesters)',
            'description' => 'Comprehensive undergraduate programmes delivered through a flexible and rigorous ODeL model.',
            'content' => 'UGX 1,000,000 per semester',
            'status' => 1,
            'sort_order' => 3,
        ],
        [
            'section_key' => 'programme_categories',
            'item_type' => 'program_category',
            'title' => 'Diploma Programmes',
            'subtitle' => '2 Academic Years (4 Semesters)',
            'description' => 'Professionally relevant diploma pathways for career growth, technical capability, and progression.',
            'content' => 'UGX 650,000 per semester',
            'status' => 1,
            'sort_order' => 4,
        ],
        [
            'section_key' => 'programme_categories',
            'item_type' => 'program_category',
            'title' => 'Certificate Programmes',
            'subtitle' => '2 Academic Years (4 Semesters)',
            'description' => 'Accessible entry-level programmes for learners beginning their higher education journey.',
            'content' => 'UGX 600,000 per semester',
            'status' => 1,
            'sort_order' => 5,
        ],
        [
            'section_key' => 'leadership_team',
            'item_type' => 'leader',
            'title' => 'Twinamatsiko Naboth, PhD.c',
            'subtitle' => 'Director',
            'description' => 'Provides overall institutional leadership, strategic direction, and external partnership stewardship for PIIE.',
            'status' => 1,
            'sort_order' => 1,
        ],
        [
            'section_key' => 'leadership_team',
            'item_type' => 'leader',
            'title' => 'Nyamurungi Naome',
            'subtitle' => 'Principal',
            'description' => 'Leads academic quality, programme integrity, curriculum oversight, and the broader academic culture of the institution.',
            'status' => 1,
            'sort_order' => 2,
        ],
        [
            'section_key' => 'leadership_team',
            'item_type' => 'leader',
            'title' => 'Academic Registrar',
            'subtitle' => 'Academic Registrar',
            'description' => 'Oversees admissions, academic records, examinations administration, and certification processes.',
            'status' => 1,
            'sort_order' => 3,
        ],
        [
            'section_key' => 'leadership_team',
            'item_type' => 'leader',
            'title' => 'Institute Secretary',
            'subtitle' => 'Institute Secretary',
            'description' => 'Coordinates governance, compliance, official records management, and administrative operations.',
            'status' => 1,
            'sort_order' => 4,
        ],
        [
            'section_key' => 'welcome_messages',
            'item_type' => 'message',
            'title' => 'Welcome Message from the Director',
            'subtitle' => 'Twinamatsiko Naboth, PhD.c',
            'description' => 'PIIE was built as a deliberate commitment to delivering the highest quality education to every learner regardless of location.',
            'content' => 'A PIIE qualification is an investment in yourself that will generate returns for the rest of your professional life.',
            'status' => 1,
            'sort_order' => 1,
        ],
        [
            'section_key' => 'welcome_messages',
            'item_type' => 'message',
            'title' => 'Welcome Message from the Principal',
            'subtitle' => 'Nyamurungi Naome',
            'description' => 'Academic excellence is built through deliberate programme design, engaged faculty, rigorous assessment, and learner-centred planning.',
            'content' => 'Approach your studies at PIIE with commitment, curiosity, and courage. We are here to challenge and support you.',
            'status' => 1,
            'sort_order' => 2,
        ],
        [
            'section_key' => 'welcome_messages',
            'item_type' => 'message',
            'title' => 'Welcome Message from the Academic Registrar',
            'subtitle' => 'Office of the Academic Registrar',
            'description' => 'Academic integrity, efficient records management, transparent admissions, and reliable certification are central to the learner experience.',
            'content' => 'Your academic records are protected, your credentials are secure, and your progress is managed with diligence and care.',
            'status' => 1,
            'sort_order' => 3,
        ],
        [
            'section_key' => 'welcome_messages',
            'item_type' => 'message',
            'title' => 'Welcome Message from the Institute Secretary',
            'subtitle' => 'Office of the Institute Secretary',
            'description' => 'Strong governance, compliance, and administrative transparency are treated as prerequisites for lasting academic quality.',
            'content' => 'We welcome scrutiny, engagement, and partnership as PIIE builds a strong and credible institutional foundation.',
            'status' => 1,
            'sort_order' => 4,
        ],
        [
            'section_key' => 'partnerships_affiliations',
            'item_type' => 'partner',
            'title' => 'Team University, Kampala, Uganda',
            'description' => 'Academic partnership for programme delivery, validation, and qualification recognition.',
            'status' => 1,
            'sort_order' => 1,
        ],
        [
            'section_key' => 'partnerships_affiliations',
            'item_type' => 'partner',
            'title' => 'Equity Group Holdings Uganda',
            'description' => 'Student financial inclusion and educational financing support.',
            'status' => 1,
            'sort_order' => 2,
        ],
        [
            'section_key' => 'partnerships_affiliations',
            'item_type' => 'partner',
            'title' => 'SurePay Limited',
            'description' => 'Technology partnership for secure and seamless online payments.',
            'status' => 1,
            'sort_order' => 3,
        ],
        [
            'section_key' => 'partnerships_affiliations',
            'item_type' => 'partner',
            'title' => 'Uganda Vocational Training and Apprenticeship Board (UVTAB)',
            'description' => 'Alignment with national skills and qualifications frameworks.',
            'status' => 1,
            'sort_order' => 4,
        ],
        [
            'section_key' => 'partnerships_affiliations',
            'item_type' => 'partner',
            'title' => 'Ministry of Education and Sports, Uganda',
            'description' => 'Regulatory compliance within Uganda\'s higher education framework.',
            'status' => 1,
            'sort_order' => 5,
        ],
        [
            'section_key' => 'partnerships_affiliations',
            'item_type' => 'partner',
            'title' => 'Uganda Registration Services Bureau (URSB)',
            'description' => 'Institutional legal registration and compliance.',
            'status' => 1,
            'sort_order' => 6,
        ],
        [
            'section_key' => 'faqs',
            'item_type' => 'faq',
            'title' => 'What is Prime International Institute of Excellence (PIIE)?',
            'description' => 'PIIE is a modern higher education institution established in Uganda in 2026, committed to internationally benchmarked programmes from Certificate to Masters level through the ODeL model.',
            'status' => 1,
            'sort_order' => 1,
        ],
        [
            'section_key' => 'faqs',
            'item_type' => 'faq',
            'title' => 'Is PIIE a recognised institution?',
            'description' => 'PIIE operates within Uganda\'s higher education regulatory framework and its programmes are validated in partnership with accredited universities.',
            'status' => 1,
            'sort_order' => 2,
        ],
        [
            'section_key' => 'faqs',
            'item_type' => 'faq',
            'title' => 'How are PIIE programmes delivered?',
            'description' => 'All programmes are delivered entirely online through the ODeL model using the PIIE Learning Management System and related digital academic platforms.',
            'status' => 1,
            'sort_order' => 3,
        ],
        [
            'section_key' => 'faqs',
            'item_type' => 'faq',
            'title' => 'Can I transfer credits from a previous qualification?',
            'description' => 'Yes. Relevant postgraduate diploma and diploma holders may qualify for advanced standing subject to individual assessment by the PIIE Credit Transfer and Admissions Committee.',
            'status' => 1,
            'sort_order' => 4,
        ],
        [
            'section_key' => 'faqs',
            'item_type' => 'faq',
            'title' => 'Is the ODeL model suitable for working professionals?',
            'description' => 'Yes. The model is specifically designed for working professionals with 24/7 access to materials, recorded live sessions, and flexible study planning.',
            'status' => 1,
            'sort_order' => 5,
        ],
        [
            'section_key' => 'faqs',
            'item_type' => 'faq',
            'title' => 'Where is PIIE located?',
            'description' => 'PIIE is headquartered in Nansana Municipality, Wakiso District, Uganda, while serving learners nationally and internationally through fully online delivery.',
            'status' => 1,
            'sort_order' => 6,
        ],
        [
            'section_key' => 'quick_links',
            'item_type' => 'quick_link',
            'title' => 'Home',
            'link' => '#home',
            'status' => 1,
            'sort_order' => 1,
        ],
        [
            'section_key' => 'quick_links',
            'item_type' => 'quick_link',
            'title' => 'About',
            'link' => '#about',
            'status' => 1,
            'sort_order' => 2,
        ],
        [
            'section_key' => 'quick_links',
            'item_type' => 'quick_link',
            'title' => 'Programmes',
            'link' => '#programs',
            'status' => 1,
            'sort_order' => 3,
        ],
        [
            'section_key' => 'quick_links',
            'item_type' => 'quick_link',
            'title' => 'Admissions',
            'link' => '#admissions',
            'status' => 1,
            'sort_order' => 4,
        ],
        [
            'section_key' => 'quick_links',
            'item_type' => 'quick_link',
            'title' => 'Research',
            'link' => '#research_innovation',
            'status' => 1,
            'sort_order' => 5,
        ],
        [
            'section_key' => 'quick_links',
            'item_type' => 'quick_link',
            'title' => 'Contact',
            'link' => '#contact',
            'status' => 1,
            'sort_order' => 6,
        ],
        [
            'section_key' => 'portals_links',
            'item_type' => 'portal',
            'title' => 'Online Admissions Portal',
            'link' => '#admissions',
            'status' => 1,
            'sort_order' => 1,
        ],
        [
            'section_key' => 'portals_links',
            'item_type' => 'portal',
            'title' => 'Student Portal',
            'link' => '/login',
            'status' => 1,
            'sort_order' => 2,
        ],
        [
            'section_key' => 'portals_links',
            'item_type' => 'portal',
            'title' => 'Learning Management System',
            'link' => '/login',
            'status' => 1,
            'sort_order' => 3,
        ],
        [
            'section_key' => 'social_media_links',
            'item_type' => 'social',
            'title' => 'Facebook',
            'link' => '#',
            'status' => 1,
            'sort_order' => 1,
        ],
        [
            'section_key' => 'social_media_links',
            'item_type' => 'social',
            'title' => 'LinkedIn',
            'link' => '#',
            'status' => 1,
            'sort_order' => 2,
        ],
        [
            'section_key' => 'social_media_links',
            'item_type' => 'social',
            'title' => 'YouTube',
            'link' => '#',
            'status' => 1,
            'sort_order' => 3,
        ],
        [
            'section_key' => 'social_media_links',
            'item_type' => 'social',
            'title' => 'Instagram',
            'link' => '#',
            'status' => 1,
            'sort_order' => 4,
        ],
    ],
    'settings' => [
        'institution_name' => 'Prime International Institute of Excellence (PIIE)',
        'tagline' => 'Internationally Benchmarked Education for Global Excellence',
        'motto' => 'Strive. Excel. Lead.',
        'contact_address' => 'Nansana Municipality, Wakiso District, Uganda',
        'director_name' => 'Twinamatsiko Naboth, PhD.c',
        'principal_name' => 'Nyamurungi Naome',
        'academic_registrar_name' => 'Academic Registrar',
        'institute_secretary_name' => 'Institute Secretary',
        'footer_copyright' => '© Prime International Institute of Excellence (PIIE). All Rights Reserved.',
        'hero_badge' => 'Open, Distance and e-Learning (ODeL)',
        'program_delivery_label' => 'FULLY ONLINE / ODeL',
    ],
];