@extends('admin.navigation')
@section('content')
<div class="mainSection-title"><div class="row"><div class="col-12 d-flex justify-content-between align-items-center"><h4>{{ get_phrase('Question Metadata') }}</h4><a class="export_btn" href="{{ route('admin.question_bank.index') }}">{{ get_phrase('Back to Question Bank') }}</a></div></div></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="row g-3">
 <div class="col-lg-4"><div class="eSection-wrap"><h6>{{ get_phrase('Create Topic') }}</h6><form method="POST" action="{{ route('admin.question_bank.metadata.topics.store') }}">@csrf<select class="form-select mb-2" name="subject_id" required><option value="">{{ get_phrase('Select Course') }}</option>@foreach($subjects as $subject)<option value="{{ $subject->id }}">{{ $subject->name }}</option>@endforeach</select><input class="form-control mb-2" name="name" maxlength="150" placeholder="Topic name" required><button class="eBtn eBtn-primary" type="submit">{{ get_phrase('Create Topic') }}</button></form></div></div>
 <div class="col-lg-4"><div class="eSection-wrap"><h6>{{ get_phrase('Create Subtopic') }}</h6><form method="POST" action="{{ route('admin.question_bank.metadata.subtopics.store') }}">@csrf<select class="form-select mb-2" name="subject_id" required><option value="">{{ get_phrase('Select Course') }}</option>@foreach($subjects as $subject)<option value="{{ $subject->id }}">{{ $subject->name }}</option>@endforeach</select><select class="form-select mb-2" name="parent_id" required><option value="">{{ get_phrase('Select Topic') }}</option>@foreach($topics->whereNull('parent_id')->where('is_active', true) as $topic)<option value="{{ $topic->id }}">{{ optional($topic->subject)->name }} — {{ $topic->name }}</option>@endforeach</select><input class="form-control mb-2" name="name" maxlength="150" placeholder="Subtopic name" required><button class="eBtn eBtn-primary" type="submit">{{ get_phrase('Create Subtopic') }}</button></form></div></div>
 <div class="col-lg-4"><div class="eSection-wrap"><h6>{{ get_phrase('Create Tag') }}</h6><form method="POST" action="{{ route('admin.question_bank.metadata.tags.store') }}">@csrf<input class="form-control mb-2" name="name" maxlength="100" placeholder="Tag name" required><button class="eBtn eBtn-primary" type="submit">{{ get_phrase('Create Tag') }}</button></form></div></div>
 <div class="col-12"><div class="eSection-wrap"><h6>{{ get_phrase('Topics and Subtopics') }}</h6><div class="table-responsive"><table class="table eTable"><thead><tr><th>Course</th><th>Name</th><th>Level</th><th>Status</th><th>Actions</th></tr></thead><tbody>@forelse($topics as $topic)<tr><td>{{ optional($topic->subject)->name }}</td><td><form method="POST" action="{{ route('admin.question_bank.metadata.topics.update', $topic->id) }}" class="d-flex gap-1">@csrf @method('PUT')<input class="form-control form-control-sm" name="name" value="{{ $topic->name }}" required><input type="hidden" name="subject_id" value="{{ $topic->subject_id }}"><button class="btn btn-sm btn-outline-primary" type="submit">{{ get_phrase('Rename') }}</button></form></td><td>{{ $topic->parent_id ? get_phrase('Subtopic') : get_phrase('Topic') }}</td><td>{{ $topic->is_active ? get_phrase('Active') : get_phrase('Inactive') }}</td><td><form method="POST" action="{{ route('admin.question_bank.metadata.topics.toggle', $topic->id) }}" class="d-inline">@csrf<button class="btn btn-sm btn-outline-secondary" type="submit">{{ $topic->is_active ? get_phrase('Deactivate') : get_phrase('Reactivate') }}</button></form></td></tr>@empty<tr><td colspan="5" class="text-center">{{ get_phrase('No topics yet') }}</td></tr>@endforelse</tbody></table></div></div></div>
 <div class="col-12"><div class="eSection-wrap"><h6>{{ get_phrase('Tags') }}</h6><div class="table-responsive"><table class="table eTable"><thead><tr><th>Name</th><th>Normalized</th><th>Status</th><th>Actions</th></tr></thead><tbody>@forelse($tags as $tag)<tr><td><form method="POST" action="{{ route('admin.question_bank.metadata.tags.update', $tag->id) }}" class="d-flex gap-1">@csrf @method('PUT')<input class="form-control form-control-sm" name="name" value="{{ $tag->name }}" required><button class="btn btn-sm btn-outline-primary" type="submit">{{ get_phrase('Rename') }}</button></form></td><td>{{ $tag->normalized_name }}</td><td>{{ $tag->is_active ? get_phrase('Active') : get_phrase('Inactive') }}</td><td><form method="POST" action="{{ route('admin.question_bank.metadata.tags.toggle', $tag->id) }}" class="d-inline">@csrf<button class="btn btn-sm btn-outline-secondary" type="submit">{{ $tag->is_active ? get_phrase('Deactivate') : get_phrase('Reactivate') }}</button></form></td></tr>@empty<tr><td colspan="4" class="text-center">{{ get_phrase('No tags yet') }}</td></tr>@endforelse</tbody></table></div></div></div>
</div>
@endsection
