<?php

// Country list used by the applicant registration/application flow for
// phone dial-code, nationality, and country-of-residence dropdowns.
return [
    ['name' => 'Afghanistan', 'dial_code' => '+93', 'nationality' => 'Afghan'],
    ['name' => 'Albania', 'dial_code' => '+355', 'nationality' => 'Albanian'],
    ['name' => 'Algeria', 'dial_code' => '+213', 'nationality' => 'Algerian'],
    ['name' => 'Andorra', 'dial_code' => '+376', 'nationality' => 'Andorran'],
    ['name' => 'Angola', 'dial_code' => '+244', 'nationality' => 'Angolan'],
    ['name' => 'Antigua and Barbuda', 'dial_code' => '+1268', 'nationality' => 'Antiguan or Barbudan'],
    ['name' => 'Argentina', 'dial_code' => '+54', 'nationality' => 'Argentine'],
    ['name' => 'Armenia', 'dial_code' => '+374', 'nationality' => 'Armenian'],
    ['name' => 'Australia', 'dial_code' => '+61', 'nationality' => 'Australian'],
    ['name' => 'Austria', 'dial_code' => '+43', 'nationality' => 'Austrian'],
    ['name' => 'Azerbaijan', 'dial_code' => '+994', 'nationality' => 'Azerbaijani'],
    ['name' => 'Bahamas', 'dial_code' => '+1242', 'nationality' => 'Bahamian'],
    ['name' => 'Bahrain', 'dial_code' => '+973', 'nationality' => 'Bahraini'],
    ['name' => 'Bangladesh', 'dial_code' => '+880', 'nationality' => 'Bangladeshi'],
    ['name' => 'Barbados', 'dial_code' => '+1246', 'nationality' => 'Barbadian'],
    ['name' => 'Belarus', 'dial_code' => '+375', 'nationality' => 'Belarusian'],
    ['name' => 'Belgium', 'dial_code' => '+32', 'nationality' => 'Belgian'],
    ['name' => 'Belize', 'dial_code' => '+501', 'nationality' => 'Belizean'],
    ['name' => 'Benin', 'dial_code' => '+229', 'nationality' => 'Beninese'],
    ['name' => 'Bhutan', 'dial_code' => '+975', 'nationality' => 'Bhutanese'],
    ['name' => 'Bolivia', 'dial_code' => '+591', 'nationality' => 'Bolivian'],
    ['name' => 'Bosnia and Herzegovina', 'dial_code' => '+387', 'nationality' => 'Bosnian or Herzegovinian'],
    ['name' => 'Botswana', 'dial_code' => '+267', 'nationality' => 'Motswana'],
    ['name' => 'Brazil', 'dial_code' => '+55', 'nationality' => 'Brazilian'],
    ['name' => 'Brunei', 'dial_code' => '+673', 'nationality' => 'Bruneian'],
    ['name' => 'Bulgaria', 'dial_code' => '+359', 'nationality' => 'Bulgarian'],
    ['name' => 'Burkina Faso', 'dial_code' => '+226', 'nationality' => 'Burkinabe'],
    ['name' => 'Burundi', 'dial_code' => '+257', 'nationality' => 'Burundian'],
    ['name' => 'Cabo Verde', 'dial_code' => '+238', 'nationality' => 'Cabo Verdean'],
    ['name' => 'Cambodia', 'dial_code' => '+855', 'nationality' => 'Cambodian'],
    ['name' => 'Cameroon', 'dial_code' => '+237', 'nationality' => 'Cameroonian'],
    ['name' => 'Canada', 'dial_code' => '+1', 'nationality' => 'Canadian'],
    ['name' => 'Central African Republic', 'dial_code' => '+236', 'nationality' => 'Central African'],
    ['name' => 'Chad', 'dial_code' => '+235', 'nationality' => 'Chadian'],
    ['name' => 'Chile', 'dial_code' => '+56', 'nationality' => 'Chilean'],
    ['name' => 'China', 'dial_code' => '+86', 'nationality' => 'Chinese'],
    ['name' => 'Colombia', 'dial_code' => '+57', 'nationality' => 'Colombian'],
    ['name' => 'Comoros', 'dial_code' => '+269', 'nationality' => 'Comoran'],
    ['name' => 'Congo (Republic of the)', 'dial_code' => '+242', 'nationality' => 'Congolese'],
    ['name' => 'Congo (Democratic Republic)', 'dial_code' => '+243', 'nationality' => 'Congolese'],
    ['name' => 'Costa Rica', 'dial_code' => '+506', 'nationality' => 'Costa Rican'],
    ['name' => 'Cote d\'Ivoire', 'dial_code' => '+225', 'nationality' => 'Ivorian'],
    ['name' => 'Croatia', 'dial_code' => '+385', 'nationality' => 'Croatian'],
    ['name' => 'Cuba', 'dial_code' => '+53', 'nationality' => 'Cuban'],
    ['name' => 'Cyprus', 'dial_code' => '+357', 'nationality' => 'Cypriot'],
    ['name' => 'Czech Republic', 'dial_code' => '+420', 'nationality' => 'Czech'],
    ['name' => 'Denmark', 'dial_code' => '+45', 'nationality' => 'Danish'],
    ['name' => 'Djibouti', 'dial_code' => '+253', 'nationality' => 'Djiboutian'],
    ['name' => 'Dominica', 'dial_code' => '+1767', 'nationality' => 'Dominican'],
    ['name' => 'Dominican Republic', 'dial_code' => '+1809', 'nationality' => 'Dominican'],
    ['name' => 'Ecuador', 'dial_code' => '+593', 'nationality' => 'Ecuadorian'],
    ['name' => 'Egypt', 'dial_code' => '+20', 'nationality' => 'Egyptian'],
    ['name' => 'El Salvador', 'dial_code' => '+503', 'nationality' => 'Salvadoran'],
    ['name' => 'Equatorial Guinea', 'dial_code' => '+240', 'nationality' => 'Equatorial Guinean'],
    ['name' => 'Eritrea', 'dial_code' => '+291', 'nationality' => 'Eritrean'],
    ['name' => 'Estonia', 'dial_code' => '+372', 'nationality' => 'Estonian'],
    ['name' => 'Eswatini', 'dial_code' => '+268', 'nationality' => 'Swazi'],
    ['name' => 'Ethiopia', 'dial_code' => '+251', 'nationality' => 'Ethiopian'],
    ['name' => 'Fiji', 'dial_code' => '+679', 'nationality' => 'Fijian'],
    ['name' => 'Finland', 'dial_code' => '+358', 'nationality' => 'Finnish'],
    ['name' => 'France', 'dial_code' => '+33', 'nationality' => 'French'],
    ['name' => 'Gabon', 'dial_code' => '+241', 'nationality' => 'Gabonese'],
    ['name' => 'Gambia', 'dial_code' => '+220', 'nationality' => 'Gambian'],
    ['name' => 'Georgia', 'dial_code' => '+995', 'nationality' => 'Georgian'],
    ['name' => 'Germany', 'dial_code' => '+49', 'nationality' => 'German'],
    ['name' => 'Ghana', 'dial_code' => '+233', 'nationality' => 'Ghanaian'],
    ['name' => 'Greece', 'dial_code' => '+30', 'nationality' => 'Greek'],
    ['name' => 'Grenada', 'dial_code' => '+1473', 'nationality' => 'Grenadian'],
    ['name' => 'Guatemala', 'dial_code' => '+502', 'nationality' => 'Guatemalan'],
    ['name' => 'Guinea', 'dial_code' => '+224', 'nationality' => 'Guinean'],
    ['name' => 'Guinea-Bissau', 'dial_code' => '+245', 'nationality' => 'Bissau-Guinean'],
    ['name' => 'Guyana', 'dial_code' => '+592', 'nationality' => 'Guyanese'],
    ['name' => 'Haiti', 'dial_code' => '+509', 'nationality' => 'Haitian'],
    ['name' => 'Honduras', 'dial_code' => '+504', 'nationality' => 'Honduran'],
    ['name' => 'Hungary', 'dial_code' => '+36', 'nationality' => 'Hungarian'],
    ['name' => 'Iceland', 'dial_code' => '+354', 'nationality' => 'Icelandic'],
    ['name' => 'India', 'dial_code' => '+91', 'nationality' => 'Indian'],
    ['name' => 'Indonesia', 'dial_code' => '+62', 'nationality' => 'Indonesian'],
    ['name' => 'Iran', 'dial_code' => '+98', 'nationality' => 'Iranian'],
    ['name' => 'Iraq', 'dial_code' => '+964', 'nationality' => 'Iraqi'],
    ['name' => 'Ireland', 'dial_code' => '+353', 'nationality' => 'Irish'],
    ['name' => 'Israel', 'dial_code' => '+972', 'nationality' => 'Israeli'],
    ['name' => 'Italy', 'dial_code' => '+39', 'nationality' => 'Italian'],
    ['name' => 'Jamaica', 'dial_code' => '+1876', 'nationality' => 'Jamaican'],
    ['name' => 'Japan', 'dial_code' => '+81', 'nationality' => 'Japanese'],
    ['name' => 'Jordan', 'dial_code' => '+962', 'nationality' => 'Jordanian'],
    ['name' => 'Kazakhstan', 'dial_code' => '+7', 'nationality' => 'Kazakhstani'],
    ['name' => 'Kenya', 'dial_code' => '+254', 'nationality' => 'Kenyan'],
    ['name' => 'Kiribati', 'dial_code' => '+686', 'nationality' => 'I-Kiribati'],
    ['name' => 'Kosovo', 'dial_code' => '+383', 'nationality' => 'Kosovar'],
    ['name' => 'Kuwait', 'dial_code' => '+965', 'nationality' => 'Kuwaiti'],
    ['name' => 'Kyrgyzstan', 'dial_code' => '+996', 'nationality' => 'Kyrgyzstani'],
    ['name' => 'Laos', 'dial_code' => '+856', 'nationality' => 'Lao'],
    ['name' => 'Latvia', 'dial_code' => '+371', 'nationality' => 'Latvian'],
    ['name' => 'Lebanon', 'dial_code' => '+961', 'nationality' => 'Lebanese'],
    ['name' => 'Lesotho', 'dial_code' => '+266', 'nationality' => 'Basotho'],
    ['name' => 'Liberia', 'dial_code' => '+231', 'nationality' => 'Liberian'],
    ['name' => 'Libya', 'dial_code' => '+218', 'nationality' => 'Libyan'],
    ['name' => 'Liechtenstein', 'dial_code' => '+423', 'nationality' => 'Liechtensteiner'],
    ['name' => 'Lithuania', 'dial_code' => '+370', 'nationality' => 'Lithuanian'],
    ['name' => 'Luxembourg', 'dial_code' => '+352', 'nationality' => 'Luxembourgish'],
    ['name' => 'Madagascar', 'dial_code' => '+261', 'nationality' => 'Malagasy'],
    ['name' => 'Malawi', 'dial_code' => '+265', 'nationality' => 'Malawian'],
    ['name' => 'Malaysia', 'dial_code' => '+60', 'nationality' => 'Malaysian'],
    ['name' => 'Maldives', 'dial_code' => '+960', 'nationality' => 'Maldivian'],
    ['name' => 'Mali', 'dial_code' => '+223', 'nationality' => 'Malian'],
    ['name' => 'Malta', 'dial_code' => '+356', 'nationality' => 'Maltese'],
    ['name' => 'Marshall Islands', 'dial_code' => '+692', 'nationality' => 'Marshallese'],
    ['name' => 'Mauritania', 'dial_code' => '+222', 'nationality' => 'Mauritanian'],
    ['name' => 'Mauritius', 'dial_code' => '+230', 'nationality' => 'Mauritian'],
    ['name' => 'Mexico', 'dial_code' => '+52', 'nationality' => 'Mexican'],
    ['name' => 'Micronesia', 'dial_code' => '+691', 'nationality' => 'Micronesian'],
    ['name' => 'Moldova', 'dial_code' => '+373', 'nationality' => 'Moldovan'],
    ['name' => 'Monaco', 'dial_code' => '+377', 'nationality' => 'Monegasque'],
    ['name' => 'Mongolia', 'dial_code' => '+976', 'nationality' => 'Mongolian'],
    ['name' => 'Montenegro', 'dial_code' => '+382', 'nationality' => 'Montenegrin'],
    ['name' => 'Morocco', 'dial_code' => '+212', 'nationality' => 'Moroccan'],
    ['name' => 'Mozambique', 'dial_code' => '+258', 'nationality' => 'Mozambican'],
    ['name' => 'Myanmar', 'dial_code' => '+95', 'nationality' => 'Burmese'],
    ['name' => 'Namibia', 'dial_code' => '+264', 'nationality' => 'Namibian'],
    ['name' => 'Nauru', 'dial_code' => '+674', 'nationality' => 'Nauruan'],
    ['name' => 'Nepal', 'dial_code' => '+977', 'nationality' => 'Nepali'],
    ['name' => 'Netherlands', 'dial_code' => '+31', 'nationality' => 'Dutch'],
    ['name' => 'New Zealand', 'dial_code' => '+64', 'nationality' => 'New Zealander'],
    ['name' => 'Nicaragua', 'dial_code' => '+505', 'nationality' => 'Nicaraguan'],
    ['name' => 'Niger', 'dial_code' => '+227', 'nationality' => 'Nigerien'],
    ['name' => 'Nigeria', 'dial_code' => '+234', 'nationality' => 'Nigerian'],
    ['name' => 'North Korea', 'dial_code' => '+850', 'nationality' => 'North Korean'],
    ['name' => 'North Macedonia', 'dial_code' => '+389', 'nationality' => 'Macedonian'],
    ['name' => 'Norway', 'dial_code' => '+47', 'nationality' => 'Norwegian'],
    ['name' => 'Oman', 'dial_code' => '+968', 'nationality' => 'Omani'],
    ['name' => 'Pakistan', 'dial_code' => '+92', 'nationality' => 'Pakistani'],
    ['name' => 'Palau', 'dial_code' => '+680', 'nationality' => 'Palauan'],
    ['name' => 'Palestine', 'dial_code' => '+970', 'nationality' => 'Palestinian'],
    ['name' => 'Panama', 'dial_code' => '+507', 'nationality' => 'Panamanian'],
    ['name' => 'Papua New Guinea', 'dial_code' => '+675', 'nationality' => 'Papua New Guinean'],
    ['name' => 'Paraguay', 'dial_code' => '+595', 'nationality' => 'Paraguayan'],
    ['name' => 'Peru', 'dial_code' => '+51', 'nationality' => 'Peruvian'],
    ['name' => 'Philippines', 'dial_code' => '+63', 'nationality' => 'Filipino'],
    ['name' => 'Poland', 'dial_code' => '+48', 'nationality' => 'Polish'],
    ['name' => 'Portugal', 'dial_code' => '+351', 'nationality' => 'Portuguese'],
    ['name' => 'Qatar', 'dial_code' => '+974', 'nationality' => 'Qatari'],
    ['name' => 'Romania', 'dial_code' => '+40', 'nationality' => 'Romanian'],
    ['name' => 'Russia', 'dial_code' => '+7', 'nationality' => 'Russian'],
    ['name' => 'Rwanda', 'dial_code' => '+250', 'nationality' => 'Rwandan'],
    ['name' => 'Saint Kitts and Nevis', 'dial_code' => '+1869', 'nationality' => 'Kittitian or Nevisian'],
    ['name' => 'Saint Lucia', 'dial_code' => '+1758', 'nationality' => 'Saint Lucian'],
    ['name' => 'Saint Vincent and the Grenadines', 'dial_code' => '+1784', 'nationality' => 'Vincentian'],
    ['name' => 'Samoa', 'dial_code' => '+685', 'nationality' => 'Samoan'],
    ['name' => 'San Marino', 'dial_code' => '+378', 'nationality' => 'Sammarinese'],
    ['name' => 'Sao Tome and Principe', 'dial_code' => '+239', 'nationality' => 'Sao Tomean'],
    ['name' => 'Saudi Arabia', 'dial_code' => '+966', 'nationality' => 'Saudi Arabian'],
    ['name' => 'Senegal', 'dial_code' => '+221', 'nationality' => 'Senegalese'],
    ['name' => 'Serbia', 'dial_code' => '+381', 'nationality' => 'Serbian'],
    ['name' => 'Seychelles', 'dial_code' => '+248', 'nationality' => 'Seychellois'],
    ['name' => 'Sierra Leone', 'dial_code' => '+232', 'nationality' => 'Sierra Leonean'],
    ['name' => 'Singapore', 'dial_code' => '+65', 'nationality' => 'Singaporean'],
    ['name' => 'Slovakia', 'dial_code' => '+421', 'nationality' => 'Slovak'],
    ['name' => 'Slovenia', 'dial_code' => '+386', 'nationality' => 'Slovenian'],
    ['name' => 'Solomon Islands', 'dial_code' => '+677', 'nationality' => 'Solomon Islander'],
    ['name' => 'Somalia', 'dial_code' => '+252', 'nationality' => 'Somali'],
    ['name' => 'South Africa', 'dial_code' => '+27', 'nationality' => 'South African'],
    ['name' => 'South Korea', 'dial_code' => '+82', 'nationality' => 'South Korean'],
    ['name' => 'South Sudan', 'dial_code' => '+211', 'nationality' => 'South Sudanese'],
    ['name' => 'Spain', 'dial_code' => '+34', 'nationality' => 'Spanish'],
    ['name' => 'Sri Lanka', 'dial_code' => '+94', 'nationality' => 'Sri Lankan'],
    ['name' => 'Sudan', 'dial_code' => '+249', 'nationality' => 'Sudanese'],
    ['name' => 'Suriname', 'dial_code' => '+597', 'nationality' => 'Surinamese'],
    ['name' => 'Sweden', 'dial_code' => '+46', 'nationality' => 'Swedish'],
    ['name' => 'Switzerland', 'dial_code' => '+41', 'nationality' => 'Swiss'],
    ['name' => 'Syria', 'dial_code' => '+963', 'nationality' => 'Syrian'],
    ['name' => 'Taiwan', 'dial_code' => '+886', 'nationality' => 'Taiwanese'],
    ['name' => 'Tajikistan', 'dial_code' => '+992', 'nationality' => 'Tajikistani'],
    ['name' => 'Tanzania', 'dial_code' => '+255', 'nationality' => 'Tanzanian'],
    ['name' => 'Thailand', 'dial_code' => '+66', 'nationality' => 'Thai'],
    ['name' => 'Timor-Leste', 'dial_code' => '+670', 'nationality' => 'Timorese'],
    ['name' => 'Togo', 'dial_code' => '+228', 'nationality' => 'Togolese'],
    ['name' => 'Tonga', 'dial_code' => '+676', 'nationality' => 'Tongan'],
    ['name' => 'Trinidad and Tobago', 'dial_code' => '+1868', 'nationality' => 'Trinidadian or Tobagonian'],
    ['name' => 'Tunisia', 'dial_code' => '+216', 'nationality' => 'Tunisian'],
    ['name' => 'Turkey', 'dial_code' => '+90', 'nationality' => 'Turkish'],
    ['name' => 'Turkmenistan', 'dial_code' => '+993', 'nationality' => 'Turkmen'],
    ['name' => 'Tuvalu', 'dial_code' => '+688', 'nationality' => 'Tuvaluan'],
    ['name' => 'Uganda', 'dial_code' => '+256', 'nationality' => 'Ugandan'],
    ['name' => 'Ukraine', 'dial_code' => '+380', 'nationality' => 'Ukrainian'],
    ['name' => 'United Arab Emirates', 'dial_code' => '+971', 'nationality' => 'Emirati'],
    ['name' => 'United Kingdom', 'dial_code' => '+44', 'nationality' => 'British'],
    ['name' => 'United States', 'dial_code' => '+1', 'nationality' => 'American'],
    ['name' => 'Uruguay', 'dial_code' => '+598', 'nationality' => 'Uruguayan'],
    ['name' => 'Uzbekistan', 'dial_code' => '+998', 'nationality' => 'Uzbekistani'],
    ['name' => 'Vanuatu', 'dial_code' => '+678', 'nationality' => 'Ni-Vanuatu'],
    ['name' => 'Vatican City', 'dial_code' => '+379', 'nationality' => 'Vatican'],
    ['name' => 'Venezuela', 'dial_code' => '+58', 'nationality' => 'Venezuelan'],
    ['name' => 'Vietnam', 'dial_code' => '+84', 'nationality' => 'Vietnamese'],
    ['name' => 'Yemen', 'dial_code' => '+967', 'nationality' => 'Yemeni'],
    ['name' => 'Zambia', 'dial_code' => '+260', 'nationality' => 'Zambian'],
    ['name' => 'Zimbabwe', 'dial_code' => '+263', 'nationality' => 'Zimbabwean'],
];
