@extends('admin.navigation')

@section('content')
<div class="mainSection-title"><div><h4>{{ $cohort ? 'Edit Programme Cohort' : 'Create Programme Cohort' }}</h4><p class="text-muted">A Programme Cohort brings together students entering the same Programme through one Admissions Intake.</p><ul class="d-flex align-items-center eBreadcrumb-2"><li><a href="{{ route('admin.programme_cohorts.index') }}">Programme Cohorts</a></li><li>{{ $cohort ? 'Edit Draft' : 'Create Programme Cohort' }}</li></ul></div></div>
@if(session('error'))<div class="alert alert-danger" role="alert">{{ session('error') }}</div>@endif
@if($errors->any())<div class="alert alert-danger" role="alert"><strong>Please review the highlighted information.</strong><ul class="mb-0 mt-1">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="eSection-wrap"><form method="POST" action="{{ $cohort ? route('admin.programme_cohorts.update',$cohort->id) : route('admin.programme_cohorts.store') }}">@csrf @if($cohort)@method('PUT')@endif
    <div class="alert alert-info" role="note"><strong>Draft:</strong> Save a draft to review its details; it is not operational and has no members. <strong>Active:</strong> Activation makes the cohort available for student membership and academic placement. An approved Programme Study Plan is required.</div>
    <div class="row g-3">
        <div class="col-md-6"><label class="form-label" for="programme_id">Programme</label><select required class="form-select" name="programme_id" id="programme_id" @error('programme_id') aria-invalid="true" aria-describedby="programme-error" @enderror><option value="">Select Programme</option>@foreach($programmes as $item)<option value="{{ $item->id }}" @selected((string)old('programme_id',$cohort?->programme_id)===(string)$item->id)>{{ $item->code }} — {{ $item->name }}</option>@endforeach</select>@error('programme_id')<div id="programme-error" class="text-danger" role="alert">{{ $message }}</div>@enderror</div>
        <div class="col-md-6"><label class="form-label" for="intake_session_id">Admissions Intake</label><select required id="intake_session_id" class="form-select" name="intake_session_id" @error('intake_session_id') aria-invalid="true" aria-describedby="intake-error" @enderror><option value="">Select Admissions Intake</option>@foreach($intakes as $item)<option value="{{ $item->id }}" @selected((string)old('intake_session_id',$cohort?->intake_session_id)===(string)$item->id)>{{ $item->name }}</option>@endforeach</select>@error('intake_session_id')<div id="intake-error" class="text-danger" role="alert">{{ $message }}</div>@enderror</div>
        <div class="col-md-6"><label class="form-label" for="entry_academic_year_id">Entry Academic Year</label><select required id="entry_academic_year_id" class="form-select" name="entry_academic_year_id" @error('entry_academic_year_id') aria-invalid="true" aria-describedby="entry-year-error" @enderror><option value="">Select Entry Academic Year</option>@foreach($years as $item)<option value="{{ $item->id }}" @selected((string)old('entry_academic_year_id',$cohort?->entry_academic_year_id)===(string)$item->id)>{{ $item->label }}</option>@endforeach</select>@error('entry_academic_year_id')<div id="entry-year-error" class="text-danger" role="alert">{{ $message }}</div>@enderror</div>
        <div class="col-md-6"><label class="form-label" for="study_plan_id">Programme Study Plan</label><select required class="form-select" name="curriculum_id" id="study_plan_id"><option value="">Select Study Plan</option>@foreach($plans as $plan)<option data-programme="{{ $plan->programme_id }}" value="{{ $plan->id }}" @selected((string)old('curriculum_id',$cohort?->curriculum_id)===(string)$plan->id)>{{ $plan->version }} — {{ ucfirst($plan->status) }}</option>@endforeach</select><small class="text-muted">Options update when you choose a Programme. The selected plan must be approved before activation.</small>@if($plans->isEmpty())<div class="small text-warning mt-1">No Programme Study Plans are available yet. Create a plan for the selected Programme before you can save this cohort.</div>@endif<div class="small text-danger" id="plan-error" role="status" aria-live="polite"></div>@error('curriculum_id')<div class="text-danger" role="alert">{{ $message }}</div>@enderror</div>
        <div class="col-md-6"><label class="form-label" for="cohort-name">Cohort Name</label><input id="cohort-name" required maxlength="150" class="form-control" name="name" value="{{ old('name',$cohort?->name) }}" @error('name') aria-invalid="true" aria-describedby="cohort-name-error" @enderror>@error('name')<div id="cohort-name-error" class="text-danger" role="alert">{{ $message }}</div>@enderror</div>
        <div class="col-md-6"><label class="form-label" for="cohort-code">Cohort Code</label><input id="cohort-code" maxlength="60" pattern="[A-Za-z0-9][A-Za-z0-9._-]*" class="form-control" name="code" data-touched="{{ old('code') || $cohort ? '1' : '0' }}" value="{{ old('code',$cohort?->code ?? $suggestedCode) }}" @error('code') aria-invalid="true" aria-describedby="cohort-code-error" @enderror><small class="text-muted">Codes are unique within this institution; parallel cohorts may use different codes.</small>@error('code')<div id="cohort-code-error" class="text-danger" role="alert">{{ $message }}</div>@enderror</div>
        <div class="col-md-6"><label class="form-label" for="expected-completion-date">Expected Completion Date</label><input id="expected-completion-date" type="date" class="form-control" name="expected_completion_date" value="{{ old('expected_completion_date',$cohort?->expected_completion_date?->format('Y-m-d')) }}" @error('expected_completion_date') aria-invalid="true" aria-describedby="completion-date-error" @enderror>@error('expected_completion_date')<div id="completion-date-error" class="text-danger" role="alert">{{ $message }}</div>@enderror</div>
    </div>
    <div class="d-flex gap-2 mt-4"><button class="eBtn eBtn-primary" type="submit">{{ $cohort ? 'Save Draft' : 'Create Draft' }}</button><a class="eBtn eBtn-secondary" href="{{ $cohort ? route('admin.programme_cohorts.show',$cohort->id) : route('admin.programme_cohorts.index') }}">Cancel</a></div>
</form></div>
<script>
document.addEventListener('DOMContentLoaded',function(){const p=document.getElementById('programme_id'),s=document.getElementById('study_plan_id'),code=document.querySelector('[name="code"]'),suggestions=@json($codeSuggestions ?? []),form=s?.closest('form'),error=document.getElementById('plan-error');function filter(){const value=p.value;let count=0;[...s.options].forEach(o=>{if(!o.value)return;o.hidden=value!==''&&o.dataset.programme!==value;if(!o.hidden)count++;if(o.hidden&&o.selected)s.value='';});if(code&&!code.dataset.touched&&suggestions[value])code.value=suggestions[value];if(error)error.textContent=value&&count===0?'No Study Plan exists for this Programme. Create its plan first, then return to finish this draft.':'';}if(code){code.addEventListener('input',()=>code.dataset.touched='1');}p.addEventListener('change',filter);filter();});
</script>
@endsection
