@extends('admin.navigation')

@section('content')
<div class="mainSection-title"><div><h4>Academic Placement</h4><p class="text-muted">Record the Programme Study Plan assignment for each active student. Choose an Entry Stage and Year of Study separately; the stage does not determine the year of study.</p><ul class="d-flex align-items-center eBreadcrumb-2"><li><a href="{{ route('admin.programme_cohorts.show',$cohort->id) }}">{{ $cohort->name }}</a></li><li>Academic Placement</li></ul></div></div>
@if(session('error'))<div class="alert alert-danger" role="alert">{{ session('error') }}</div>@endif
@if($errors->any())<div class="alert alert-danger" role="alert"><strong>Please review the placement details.</strong><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="eSection-wrap"><div class="alert alert-info" role="note"><div><strong>Programme:</strong> {{ $cohort->programme?->name }}</div><div><strong>Admissions Intake:</strong> {{ $cohort->intakeSession?->name }}</div><div><strong>Programme Study Plan:</strong> {{ $cohort->studyPlan?->version }}</div><div><strong>Entry Academic Year:</strong> {{ $cohort->entryAcademicYear?->label }}</div></div>
@if($memberships->isEmpty())<div class="text-center py-4"><h5>No students ready for placement</h5><p class="text-muted">Only active students are shown. Add a student to this Programme Cohort or resume a deferred membership before recording academic placement.</p><a class="eBtn eBtn-secondary" href="{{ route('admin.programme_cohorts.show',$cohort->id) }}">Return to Programme Cohort</a></div>@else
<div class="d-none d-md-block table-responsive"><table class="table eTable align-middle"><thead><tr><th scope="col">Student</th><th scope="col">Entry Stage</th><th scope="col">Year of Study</th><th scope="col">Action</th></tr></thead><tbody>@foreach($memberships as $membership)<tr><td>{{ $membership->student?->name }}<div class="small text-muted">Active membership</div></td><td><label class="visually-hidden" for="entry-stage-{{ $membership->id }}">Entry Stage for {{ $membership->student?->name }}</label><select required form="placement-{{ $membership->id }}" id="entry-stage-{{ $membership->id }}" class="form-select" name="entry_curriculum_stage_id"><option value="">Select Entry Stage</option>@foreach($cohort->studyPlan->stages as $stage)<option value="{{ $stage->id }}">{{ $stage->label }}</option>@endforeach</select></td><td><label class="visually-hidden" for="study-year-{{ $membership->id }}">Year of Study for {{ $membership->student?->name }}</label><input required form="placement-{{ $membership->id }}" id="study-year-{{ $membership->id }}" type="number" min="1" max="255" step="1" class="form-control" name="year_of_study" placeholder="Enter year"></td><td><form id="placement-{{ $membership->id }}" method="POST" action="{{ route('admin.programme_cohorts.placement.store',[$cohort->id,$membership->id]) }}">@csrf<button class="btn btn-primary text-nowrap" type="submit">Record Placement</button></form></td></tr>@endforeach</tbody></table></div>
<div class="d-md-none">@foreach($memberships as $membership)<div class="border rounded p-3 mb-3"><h6 class="mb-1">{{ $membership->student?->name }}</h6><p class="small text-muted mb-3">Active membership · choose both academic placement values below.</p><form method="POST" action="{{ route('admin.programme_cohorts.placement.store',[$cohort->id,$membership->id]) }}">@csrf<label class="form-label" for="mobile-entry-stage-{{ $membership->id }}">Entry Stage</label><select required id="mobile-entry-stage-{{ $membership->id }}" class="form-select mb-3" name="entry_curriculum_stage_id"><option value="">Select Entry Stage</option>@foreach($cohort->studyPlan->stages as $stage)<option value="{{ $stage->id }}">{{ $stage->label }}</option>@endforeach</select><label class="form-label" for="mobile-study-year-{{ $membership->id }}">Year of Study</label><input required id="mobile-study-year-{{ $membership->id }}" type="number" min="1" max="255" step="1" class="form-control mb-3" name="year_of_study" placeholder="Enter Year of Study"><button class="btn btn-primary w-100" type="submit">Record Placement</button></form></div>@endforeach</div>@endif</div>
@endsection
