@extends('admin.navigation')
@section('content')
@php
    $editable = $offering->status === 'draft';
@endphp
<div class="mainSection-title"><div class="d-flex justify-content-between align-items-start flex-wrap gap-3"><div><h4>{{ $offering->reference ?: 'Course Offering' }}</h4></div><div class="d-flex flex-wrap gap-2">@if($canCreateLiveClass)<a class="btn btn-primary" href="{{ route('admin.course_offerings.live_classes.create', $offering->id) }}">{{ get_phrase('Schedule Live Class') }}</a>@endif<a class="btn btn-outline-secondary" href="{{ route('admin.course_offerings.index') }}">{{ get_phrase('All Offerings') }}</a></div></div></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="alert alert-info" role="status"><strong>Next step:</strong> {{ $nextStep }}</div>
<section class="eSection-wrap mb-3" aria-label="Course Offering overview">
    <div class="row g-3 align-items-stretch">
        <div class="col-12 col-lg-6"><h5>{{ $courseUnitLabel }}</h5><div class="fs-5">{{ $offering->subject->code ? $offering->subject->code.' — ' : '' }}{{ $offering->subject->name }}</div><div class="text-muted mt-1"><strong>Offering Reference:</strong> {{ $offering->reference ?: '—' }}</div><div class="text-muted mt-1"><strong>Academic Year:</strong> {{ $offering->academicYear->label }} · <strong>{{ $periodLabel }}:</strong> {{ $offering->academicPeriod->label }}</div><div class="mt-2"><span class="badge bg-primary">{{ str_replace('_',' ',ucfirst($offering->status)) }}</span></div></div>
        <div class="col-6 col-lg-3"><h6>Registered Students</h6><div class="fs-3">{{ $canViewRegistrations ? $registeredStudentCount : '—' }}</div>@if($canViewRegistrations)<a href="{{ route('admin.course_offerings.registrations', $offering->id) }}">Open registered students</a>@else<span class="text-muted small">Permission required</span>@endif</div>
        <div class="col-6 col-lg-3"><h6>Eligible Students</h6><div class="fs-3">{{ $canViewRegistrations ? $eligibleStudents->count() : '—' }}</div>@if($canViewRegistrations)<a href="{{ route('admin.course_offerings.eligible_students', $offering->id) }}">Review eligible students</a>@else<span class="text-muted small">Permission required</span>@endif</div>
    </div>
    @if($canViewRegistrations && $registeredStudents->isEmpty())<div class="alert alert-info mt-3 mb-0" role="status"><strong>No students are registered for this Course Offering yet.</strong> Review eligible students to begin Course Registration. <a href="{{ route('admin.course_offerings.eligible_students', $offering->id) }}" class="alert-link">Review eligible students</a>.</div>@endif
    <hr><div class="d-flex flex-wrap gap-2">@if(auth()->user()->hasPermission('academic.course_offering.lecturer.view'))<a class="btn btn-outline-primary" href="{{ route('admin.course_offerings.lecturers.index', $offering->id) }}">Teaching Team</a>@endif @if($canViewRegistrations)<a class="btn btn-outline-primary" href="{{ route('admin.course_offerings.eligible_students', $offering->id) }}">Eligible Students</a><a class="btn btn-outline-primary" href="{{ route('admin.course_offerings.registrations', $offering->id) }}">Registered Students</a>@endif</div>
</section>
@if(auth()->user()->hasPermission('academic.course_offering.lecturer.view'))
<section class="eSection-wrap mb-3"><div class="d-flex justify-content-between align-items-center flex-wrap gap-2"><h5 class="mb-0">Teaching Team</h5><a class="btn btn-sm btn-outline-primary" href="{{ route('admin.course_offerings.lecturers.index', $offering->id) }}">{{ auth()->user()->hasPermission('academic.course_offering.lecturer.manage') ? 'Manage Lecturer Allocations' : 'View Teaching Team' }}</a></div>
    @if($activeTeachingTeam->isEmpty())<p class="text-muted mt-3 mb-0">No lecturers have been assigned yet.</p>@else<div class="table-responsive mt-2"><table class="table mb-0"><thead><tr><th>Lecturer</th><th>Role</th><th>Effective dates</th></tr></thead><tbody>@foreach($activeTeachingTeam as $allocation)<tr><td>{{ $allocation->lecturer?->name ?: 'Former lecturer' }}</td><td>{{ $roleLabels[$allocation->role] ?? str_replace('_',' ',$allocation->role) }}</td><td>{{ $allocation->starts_on?->format('Y-m-d') }} – {{ $allocation->ends_on?->format('Y-m-d') ?: 'No end date' }}</td></tr>@endforeach</tbody></table></div>@endif
</section>
@endif
<section class="eSection-wrap mb-3" id="live-classes" aria-labelledby="live-classes-heading">
    <div class="d-flex justify-content-between align-items-start flex-wrap gap-2 mb-3">
        <div><h5 id="live-classes-heading">{{ get_phrase('Live Classes') }}</h5></div>
    </div>
    @if($liveClasses->isEmpty())
        <div class="border rounded p-4 text-center" role="status"><h6>{{ get_phrase('No live classes scheduled') }}</h6><p class="text-muted mb-0">{{ get_phrase('No live classes have been scheduled for this course offering yet.') }}</p></div>
    @else
        @foreach($liveClassGroups as $groupLabel => $sessions)
            @if($sessions->isNotEmpty())
                <section class="mb-3" aria-label="{{ get_phrase($groupLabel) }}">
                    <h6>{{ get_phrase($groupLabel) }} <span class="text-muted">({{ $sessions->count() }})</span></h6>
                    @foreach($sessions as $liveClass)
                        @include('admin.live_class._offering_session', ['liveClass' => $liveClass])
                    @endforeach
                </section>
            @endif
        @endforeach
    @endif
</section>
<section class="eSection-wrap mb-3" id="offering-details"><h5>Offering Details</h5>@if($editable && auth()->user()->hasPermission('academic.course_offering.manage'))
<form method="POST" action="{{ route('admin.course_offerings.update',$offering->id) }}" class="row g-2">@csrf @method('PUT')<div class="col-md-3"><label class="form-label">Course Unit</label><select class="form-select" name="subject_id">@foreach($subjects as $subject)<option value="{{ $subject->id }}" @selected($offering->subject_id==$subject->id)>{{ $subject->code ? $subject->code.' — ' : '' }}{{ $subject->name }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Academic Year</label><select class="form-select" name="academic_year_id" id="edit-year">@foreach($years as $year)<option value="{{ $year->id }}" @selected($offering->academic_year_id==$year->id)>{{ $year->label }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Academic Period</label><select class="form-select" name="academic_period_id" id="edit-period">@foreach($periods as $period)<option data-year="{{ $period->academic_year_id }}" value="{{ $period->id }}" @selected($offering->academic_period_id==$period->id)>{{ $period->label }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label">Reference</label><input class="form-control" name="reference" maxlength="50" value="{{ $offering->reference }}"></div><div class="col-md-1 d-flex align-items-end"><button class="btn btn-primary">Save</button></div></form>
@else<dl class="row mb-0"><dt class="col-sm-3">Offering reference</dt><dd class="col-sm-9">{{ $offering->reference ?: '—' }}</dd></dl>@endif</section>
<section class="eSection-wrap mb-3" id="applicability"><h5>Programme Study Plan Applicability</h5><p class="text-muted">Linked Study Plans determine which students may register; teaching staff are managed separately.</p><div class="table-responsive"><table class="table"><thead><tr><th>Programme</th><th>Study Plan version</th><th>Placement</th><th></th></tr></thead><tbody>@forelse($links as $link)<tr><td>{{ $link->programme_code }} — {{ $link->programme_name }}</td><td>{{ $link->version }}</td><td>{{ $link->stage_label ?: 'Placement' }} · {{ ucfirst($link->period_type) }} {{ $link->period_sequence }} · {{ ucfirst($link->classification) }}</td><td>@if($editable && auth()->user()->hasPermission('academic.course_offering.manage'))<form method="POST" action="{{ route('admin.course_offerings.applicability.destroy',[$offering->id,$link->curriculum_membership_id]) }}" onsubmit="return confirm('Remove this applicability?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Remove</button></form>@endif</td></tr>@empty<tr><td colspan="4" class="text-muted">No Programme Study Plans have been linked to this Course Offering yet.</td></tr>@endforelse</tbody></table></div>
@if($editable && auth()->user()->hasPermission('academic.course_offering.manage'))@if($candidates->isEmpty())<p class="text-muted mb-0">No compatible approved Programme Study Plan memberships are available to link yet.</p>@else<form method="POST" action="{{ route('admin.course_offerings.applicability.store',$offering->id) }}" class="row g-2">@csrf<div class="col-md-9"><label class="form-label">Add a compatible Programme Study Plan membership</label><select class="form-select" name="curriculum_membership_id" required><option value="">Choose Programme Study Plan membership</option>@foreach($candidates as $candidate)<option value="{{ $candidate->id }}">{{ $candidate->programme_code }} — {{ $candidate->programme_name }} · v{{ $candidate->version }} · {{ ucfirst($candidate->period_type) }} {{ $candidate->period_sequence }}</option>@endforeach</select>@if($candidates->count()===100)<small class="text-muted">Showing first 100 candidates; narrow selection in the Programme Study Plan before adding.</small>@endif</div><div class="col-md-3 d-flex align-items-end"><button class="btn btn-primary">Link Study Plan</button></div></form>@endif @endif</section>
<section class="eSection-wrap mb-3" id="lifecycle"><h5>Lifecycle</h5><p class="text-muted">Draft → Open → In progress → Completed. Open, in-progress and draft Offerings may be cancelled. Open freezes identity and applicability.</p>
@if($editable && auth()->user()->hasPermission('academic.course_offering.lifecycle'))<form method="POST" action="{{ route('admin.course_offerings.open',$offering->id) }}" class="d-inline" onsubmit="return confirm('Open this Offering? Identity and applicability will be frozen.')">@csrf<button class="btn btn-success">Open Offering</button></form>@endif
@if($offering->status==='open' && auth()->user()->hasPermission('academic.course_offering.lifecycle'))<form method="POST" action="{{ route('admin.course_offerings.start',$offering->id) }}" class="d-inline">@csrf<button class="btn btn-primary">Start</button></form>@endif
@if($offering->status==='in_progress' && auth()->user()->hasPermission('academic.course_offering.lifecycle'))<form method="POST" action="{{ route('admin.course_offerings.complete',$offering->id) }}" class="d-inline" onsubmit="return confirm('Complete this Offering?')">@csrf<button class="btn btn-dark">Complete</button></form>@endif
@if(in_array($offering->status,['draft','open','in_progress'],true) && auth()->user()->hasPermission('academic.course_offering.lifecycle'))<form method="POST" action="{{ route('admin.course_offerings.cancel',$offering->id) }}" class="mt-3" onsubmit="return confirm('Cancel this Offering? This is terminal and preserves history.')">@csrf<label class="form-label" for="reason">Cancellation reason</label><textarea id="reason" name="reason" class="form-control mb-2" required maxlength="1000"></textarea><button class="btn btn-outline-danger">Cancel Offering</button></form>@endif
@if(in_array($offering->status,['completed','cancelled'],true))<p class="mb-0">Terminal historical record. This Offering is read-only.</p>@endif
</section>
<section class="eSection-wrap"><h5>Audit / History</h5><div class="table-responsive"><table class="table"><thead><tr><th>When</th><th>Action</th><th>Description</th></tr></thead><tbody>@forelse($audit as $event)<tr><td>{{ $event->created_at }}</td><td>{{ $event->action }}</td><td>{{ $event->description }}</td></tr>@empty<tr><td colspan="3" class="text-muted">No audit entries available.</td></tr>@endforelse</tbody></table></div></section>
@endsection
